//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> ActivityStatus { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public int Code { get; set; }
        public string Company { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> DueTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string LinkDoc { get; set; }
        public string LinkedTo { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Priority { get; set; }
        public string ProposedBy { get; set; }
        public Nullable<decimal> RecurringDays { get; set; }
        public string ReminderMode { get; set; }
        public Nullable<int> ReminderTick { get; set; }
        public int Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
