//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddCharges
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AppStage { get; set; }
        public string Branch { get; set; }
        public string CalOperater { get; set; }
        public string CalStage { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public string Eqsn { get; set; }
        public bool Hide { get; set; }
        public string Name { get; set; }
        public bool PerOrValue { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
