//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOns
    {
        public int RECORDKEY { get; set; }
        public string ApplCode { get; set; }
        public bool AutoCode { get; set; }
        public bool AutoDescr { get; set; }
        public string BackColor { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> Decimals { get; set; }
        public bool DontUpdate { get; set; }
        public System.DateTime EffDate { get; set; }
        public System.DateTime EffDate2 { get; set; }
        public string Eqsn { get; set; }
        public string Fld { get; set; }
        public Nullable<int> FldSize { get; set; }
        public string FldType { get; set; }
        public bool ForceUpdate { get; set; }
        public string Head { get; set; }
        public bool Hide { get; set; }
        public bool InActive { get; set; }
        public string ItemGroups { get; set; }
        public bool Lock { get; set; }
        public bool ManualChange { get; set; }
        public Nullable<int> MinPrefix { get; set; }
        public Nullable<int> MinSize { get; set; }
        public bool NoCaption { get; set; }
        public bool PlaceInLine { get; set; }
        public string PlaceValue { get; set; }
        public string Prefix { get; set; }
        public string QueryText { get; set; }
        public bool Reqd { get; set; }
        public Nullable<int> RoundedTo { get; set; }
        public bool SendEmail { get; set; }
        public bool SendSMS { get; set; }
        public int Sno { get; set; }
        public string TableKey { get; set; }
        public string Types { get; set; }
        public string Users { get; set; }
        public Nullable<int> Width { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string QueryCode { get; set; }
    }
}
