//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddonDocOthers
    {
        public int RECORDKEY { get; set; }
        public System.DateTime DocDate { get; set; }
        public string F001 { get; set; }
        public string F002 { get; set; }
        public string F003 { get; set; }
        public string F004 { get; set; }
        public string F005 { get; set; }
        public string F006 { get; set; }
        public string F007 { get; set; }
        public string F008 { get; set; }
        public string F009 { get; set; }
        public string F010 { get; set; }
        public string F011 { get; set; }
        public string F012 { get; set; }
        public string F013 { get; set; }
        public string F014 { get; set; }
        public string F015 { get; set; }
        public string ParentKey { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
