//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddonValues
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public string Fld { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public string MainType { get; set; }
        public string ParentKey { get; set; }
        public string PeriodCode { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string TableName { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
