//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllMasters
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public string Descr { get; set; }
        public Nullable<decimal> FldNum1 { get; set; }
        public Nullable<decimal> FldNum2 { get; set; }
        public string FldTxt1 { get; set; }
        public string FldTxt2 { get; set; }
        public string MasterCode { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
