//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARAPVoucher
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> aAmount { get; set; }
        public string ACode { get; set; }
        public string AFlag { get; set; }
        public string aMaintype { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string APrefix { get; set; }
        public string ArApType { get; set; }
        public string ASerial { get; set; }
        public string ASno { get; set; }
        public string aSrl { get; set; }
        public string ASubType { get; set; }
        public string AType { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> CostPer { get; set; }
        public string Flag { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string Prefix { get; set; }
        public string Sno { get; set; }
        public Nullable<int> Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
