//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaMaster
    {
        public int RECORDKEY { get; set; }
        public int Code { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Flag { get; set; }
        public int Grp { get; set; }
        public int GrpKey { get; set; }
        public bool Hide { get; set; }
        public Nullable<int> Level { get; set; }
        public bool Locked { get; set; }
        public string Name { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
