//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetToEmp
    {
        public int RECORDKEY { get; set; }
        public string AssetType { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string EmpID { get; set; }
        public int LocationCode { get; set; }
        public string Narr { get; set; }
        public Nullable<int> Returned { get; set; }
        public Nullable<decimal> ValueToEmployee { get; set; }
        public Nullable<decimal> ValueToEmployer { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
