//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetVerified
    {
        public int RECORDKEY { get; set; }
        public string Batch { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> DevAmt { get; set; }
        public Nullable<double> DevQty { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocTime { get; set; }
        public int LocationCode { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public string Reason { get; set; }
        public string RegNumber { get; set; }
        public bool Selected { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public Nullable<double> StkQty { get; set; }
        public Nullable<decimal> StkRate { get; set; }
        public int Store { get; set; }
        public string TagNo { get; set; }
        public string UserID { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
