//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetBudget
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AssetID { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> Dept { get; set; }
        public int LocationCode { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
