//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCategory
    {
        public int RECORDKEY { get; set; }
        public string Account { get; set; }
        public int Code { get; set; }
        public string DeprAccount { get; set; }
        public bool Depreciable { get; set; }
        public string DeprMethod { get; set; }
        public Nullable<decimal> DeprRate { get; set; }
        public Nullable<decimal> DeprRateIT { get; set; }
        public string Name { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
