//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        public int RECORDKEY { get; set; }
        public string AcCode { get; set; }
        public string AcDep { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public int LocationCode { get; set; }
        public string Method { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PurchDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Store { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
