//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public Nullable<System.DateTime> Docdate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryLog { get; set; }
        public string ExeInfo { get; set; }
        public string Ids { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public string Opmode { get; set; }
        public string OptionName { get; set; }
        public string Party { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Srl { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string UserID { get; set; }
        public string WorkStation { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
