//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankRules
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> BillLimit { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> ChequeLimit { get; set; }
        public bool ChqBill { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> CommRate { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> IntRate { get; set; }
        public Nullable<decimal> LimitFrom { get; set; }
        public Nullable<decimal> LimitTo { get; set; }
        public int LocationCode { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
