//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMaster
    {
        public int RECORDKEY { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string BranchCode { get; set; }
        public string City { get; set; }
        public string Cloan { get; set; }
        public int Code { get; set; }
        public string Country { get; set; }
        public string Hloan { get; set; }
        public string MICR { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string NEFT { get; set; }
        public string Oloan { get; set; }
        public string Person { get; set; }
        public string Pin { get; set; }
        public string State { get; set; }
        public string Swift { get; set; }
        public string Telephone { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
