//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchOpen
    {
        public int RECORDKEY { get; set; }
        public string ARNumber { get; set; }
        public Nullable<decimal> Assay { get; set; }
        public bool AssayType { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<double> Balance2 { get; set; }
        public string Batch { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<double> Factor { get; set; }
        public string HoldRemark { get; set; }
        public Nullable<decimal> Inward { get; set; }
        public Nullable<double> Inward2 { get; set; }
        public string InwardNumber { get; set; }
        public string ItemCategory { get; set; }
        public int LocationCode { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<double> NewRate { get; set; }
        public bool NoExpiry { get; set; }
        public Nullable<decimal> Opening { get; set; }
        public Nullable<double> Opening2 { get; set; }
        public Nullable<decimal> Outward { get; set; }
        public Nullable<double> Outward2 { get; set; }
        public string Prefix { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> SalesRate { get; set; }
        public Nullable<int> Store { get; set; }
        public Nullable<decimal> Water { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
