//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadCastMaster
    {
        public int RECORDKEY { get; set; }
        public string DocNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndTime { get; set; }
        public bool Blink { get; set; }
        public bool Scroll { get; set; }
        public string Color { get; set; }
        public string FontFamily { get; set; }
        public bool Bold { get; set; }
        public string Narr { get; set; }
        public bool Active { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
