//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budgets
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Annual { get; set; }
        public Nullable<decimal> AnnualQty { get; set; }
        public Nullable<int> Area { get; set; }
        public string Branch { get; set; }
        public string BudgetType { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public bool ControlBP { get; set; }
        public bool ControlBS { get; set; }
        public bool ControlBY { get; set; }
        public bool ControlMCP { get; set; }
        public bool ControlMCS { get; set; }
        public bool ControlMCY { get; set; }
        public Nullable<decimal> ControlToleP { get; set; }
        public Nullable<decimal> ControlToleS { get; set; }
        public Nullable<decimal> ControlToleY { get; set; }
        public bool ControlTypeP { get; set; }
        public bool ControlTypeS { get; set; }
        public bool ControlTypeY { get; set; }
        public string CostCentre { get; set; }
        public Nullable<double> Factor { get; set; }
        public string Flag { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public string ItemGroup { get; set; }
        public int LocationCode { get; set; }
        public string Party { get; set; }
        public string Prefix { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Qty1 { get; set; }
        public Nullable<decimal> Qty10 { get; set; }
        public Nullable<decimal> Qty11 { get; set; }
        public Nullable<decimal> Qty12 { get; set; }
        public Nullable<decimal> Qty2 { get; set; }
        public Nullable<decimal> Qty3 { get; set; }
        public Nullable<decimal> Qty4 { get; set; }
        public Nullable<decimal> Qty5 { get; set; }
        public Nullable<decimal> Qty6 { get; set; }
        public Nullable<decimal> Qty7 { get; set; }
        public Nullable<decimal> Qty8 { get; set; }
        public Nullable<decimal> Qty9 { get; set; }
        public Nullable<decimal> Ratio1 { get; set; }
        public Nullable<decimal> Ratio10 { get; set; }
        public Nullable<decimal> Ratio11 { get; set; }
        public Nullable<decimal> Ratio12 { get; set; }
        public Nullable<decimal> Ratio2 { get; set; }
        public Nullable<decimal> Ratio3 { get; set; }
        public Nullable<decimal> Ratio4 { get; set; }
        public Nullable<decimal> Ratio5 { get; set; }
        public Nullable<decimal> Ratio6 { get; set; }
        public Nullable<decimal> Ratio7 { get; set; }
        public Nullable<decimal> Ratio8 { get; set; }
        public Nullable<decimal> Ratio9 { get; set; }
        public Nullable<int> Salesman { get; set; }
        public Nullable<decimal> Sanctioned { get; set; }
        public string SelectFlags { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Val1 { get; set; }
        public Nullable<decimal> Val10 { get; set; }
        public Nullable<decimal> Val11 { get; set; }
        public Nullable<decimal> Val12 { get; set; }
        public Nullable<decimal> Val2 { get; set; }
        public Nullable<decimal> Val3 { get; set; }
        public Nullable<decimal> Val4 { get; set; }
        public Nullable<decimal> Val5 { get; set; }
        public Nullable<decimal> Val6 { get; set; }
        public Nullable<decimal> Val7 { get; set; }
        public Nullable<decimal> Val8 { get; set; }
        public Nullable<decimal> Val9 { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
