//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caddress
    {
        public int RECORDKEY { get; set; }
        public string AadharNo { get; set; }
        public Nullable<int> AddOrContact { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Adrl4 { get; set; }
        public Nullable<System.DateTime> AnnDate { get; set; }
        public Nullable<int> Area { get; set; }
        public string AssistEmail { get; set; }
        public string AssistMobile { get; set; }
        public string AssistName { get; set; }
        public string AssistTel { get; set; }
        public string BankNumber { get; set; }
        public string BaseGr { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<System.DateTime> ChildBdate { get; set; }
        public string ChildName { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string ContEmail { get; set; }
        public string ContMobile { get; set; }
        public string ContTelephone { get; set; }
        public string CorpID { get; set; }
        public Nullable<int> CorrespondenceType { get; set; }
        public string Country { get; set; }
        public Nullable<byte> DealerType { get; set; }
        public bool DelyFri { get; set; }
        public bool DelyMon { get; set; }
        public bool DelySat { get; set; }
        public bool DelySun { get; set; }
        public bool DelyThu { get; set; }
        public bool DelyTue { get; set; }
        public bool DelyWed { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<int> DraweeBank { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Fax { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> GSTType { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public string Instagram { get; set; }
        public bool IsContact { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> LeadCode { get; set; }
        public string LegalName { get; set; }
        public string Licence1 { get; set; }
        public string Licence2 { get; set; }
        public string LinkedIn { get; set; }
        public int LocationCode { get; set; }
        public Nullable<int> MailingCategory { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string PanNo { get; set; }
        public string Password { get; set; }
        public string Person { get; set; }
        public string PhotoPath { get; set; }
        public string Pin { get; set; }
        public string PoisonLiceno { get; set; }
        public string PTaxCode { get; set; }
        public Nullable<int> Religion { get; set; }
        public string ReraRegNo { get; set; }
        public string Segment { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public int Sno { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> SpouseBdate { get; set; }
        public string SpouseName { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string STaxCode { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string TINNo { get; set; }
        public string Tweeter { get; set; }
        public string UPINo { get; set; }
        public string UserID { get; set; }
        public string VATReg { get; set; }
        public string WhatsApp { get; set; }
        public string www { get; set; }
        public string Youtube { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
