//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public int CampaignType { get; set; }
        public int Code { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> ExpectedRevenue { get; set; }
        public string KeyProduct { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Place { get; set; }
        public Nullable<int> Salesman { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> SuccessRate { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
