//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheques
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Branch { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNumber { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> FirstCheque { get; set; }
        public int LocationCode { get; set; }
        public bool Locked { get; set; }
        public string Party { get; set; }
        public string Prefix { get; set; }
        public string Sno { get; set; }
        public Nullable<int> Srl { get; set; }
        public bool StopPayment { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
