//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosingStock
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<decimal> Issue { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public int Store { get; set; }
        public string TableKey { get; set; }
        public Nullable<decimal> Wastage { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
