//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColourScheme
    {
        public int RECORDKEY { get; set; }
        public Nullable<long> BackClr { get; set; }
        public Nullable<byte> Code { get; set; }
        public bool Deflt { get; set; }
        public Nullable<long> GridClr { get; set; }
        public Nullable<long> LabelClr { get; set; }
        public string Name { get; set; }
        public Nullable<long> Panel2Clr { get; set; }
        public Nullable<long> PanelClr { get; set; }
        public Nullable<long> SubTotalClr { get; set; }
        public Nullable<long> TotalClr { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
