//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int RECORDKEY { get; set; }
        public string AccountStatus { get; set; }
        public string Accounttype { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string Companytype { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Corrtype { get; set; }
        public Nullable<int> Currency { get; set; }
        public string Documents { get; set; }
        public string Email { get; set; }
        public string Employees { get; set; }
        public string Fax { get; set; }
        public string Homepage { get; set; }
        public string Images { get; set; }
        public bool MailRestrict { get; set; }
        public string MajorAccount { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Opportunities { get; set; }
        public string Pin { get; set; }
        public string Revenue { get; set; }
        public string Segment { get; set; }
        public Nullable<int> Source { get; set; }
        public string State { get; set; }
        public bool Status { get; set; }
        public string Strategies { get; set; }
        public string Strength { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Territory { get; set; }
        public string Threats { get; set; }
        public string Weakness { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
