//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConDetail
    {
        public int RECORDKEY { get; set; }
        public string ContrType { get; set; }
        public string CustCode { get; set; }
        public string Code { get; set; }
        public string Services { get; set; }
        public int SrNo { get; set; }
        public string WtType { get; set; }
        public Nullable<int> Wtfrom { get; set; }
        public Nullable<int> WtTo { get; set; }
        public decimal Rate { get; set; }
        public bool ChgOn { get; set; }
        public Nullable<double> Val1 { get; set; }
        public Nullable<double> Val2 { get; set; }
        public Nullable<double> Val3 { get; set; }
        public Nullable<double> Val4 { get; set; }
        public Nullable<double> Val5 { get; set; }
        public Nullable<double> Val6 { get; set; }
        public Nullable<double> Val7 { get; set; }
        public Nullable<double> Val8 { get; set; }
        public Nullable<double> Val9 { get; set; }
        public Nullable<double> Val10 { get; set; }
        public Nullable<double> Val11 { get; set; }
        public Nullable<double> Val12 { get; set; }
        public Nullable<double> Val13 { get; set; }
        public Nullable<double> Val14 { get; set; }
        public Nullable<double> Val15 { get; set; }
        public Nullable<double> Val16 { get; set; }
        public Nullable<double> Val17 { get; set; }
        public Nullable<double> Val18 { get; set; }
        public Nullable<double> Val19 { get; set; }
        public Nullable<double> Val20 { get; set; }
        public Nullable<double> Val21 { get; set; }
        public Nullable<double> Val22 { get; set; }
        public Nullable<double> Val23 { get; set; }
        public Nullable<double> Val24 { get; set; }
        public Nullable<double> Val25 { get; set; }
        public string Flg1 { get; set; }
        public string Flg2 { get; set; }
        public string Flg3 { get; set; }
        public string Flg4 { get; set; }
        public string Flg5 { get; set; }
        public string Flg6 { get; set; }
        public string Flg7 { get; set; }
        public string Flg8 { get; set; }
        public string Flg9 { get; set; }
        public string Flg10 { get; set; }
        public string Flg11 { get; set; }
        public string Flg12 { get; set; }
        public string Flg13 { get; set; }
        public string Flg14 { get; set; }
        public string Flg15 { get; set; }
        public string Flg16 { get; set; }
        public string Flg17 { get; set; }
        public string Flg18 { get; set; }
        public string Flg19 { get; set; }
        public string Flg20 { get; set; }
        public string Flg21 { get; set; }
        public string Flg22 { get; set; }
        public string Flg23 { get; set; }
        public string Flg24 { get; set; }
        public string Flg25 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public Nullable<decimal> Collection { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public Nullable<byte> Flag1 { get; set; }
        public Nullable<decimal> Hamali { get; set; }
        public string HaType { get; set; }
    }
}
