//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConMaster
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CustType { get; set; }
        public string Cust { get; set; }
        public System.DateTime DocDt { get; set; }
        public System.DateTime ContractDate { get; set; }
        public System.DateTime FromDt { get; set; }
        public System.DateTime ToDt { get; set; }
        public string FromBranch { get; set; }
        public string ToBranch { get; set; }
        public string PaymentTerms { get; set; }
        public string Remark { get; set; }
        public string TableKey { get; set; }
        public string ParentKey { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string Authenticate { get; set; }
        public string AuthorisePerson { get; set; }
        public string Dest { get; set; }
        public Nullable<System.DateTime> RefDt { get; set; }
        public string RefNo { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Source { get; set; }
    }
}
