//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consigner
    {
        public int RECORDKEY { get; set; }
        public bool Acitve { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string Branch { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string Customer { get; set; }
        public string ContactName { get; set; }
        public string ContactName2 { get; set; }
        public string ContactNO { get; set; }
        public string ContactNO2 { get; set; }
        public string District { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string ENTEREDBY { get; set; }
        public string Fax { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string Name { get; set; }
        public string Pin { get; set; }
        public Nullable<int> Pincode { get; set; }
        public bool RemarkReq { get; set; }
        public string Remark { get; set; }
        public bool HoldReq { get; set; }
        public string HoldRemark { get; set; }
        public string PAN { get; set; }
        public string GST { get; set; }
        public bool TickLrConsignor { get; set; }
        public bool TickLrConsignee { get; set; }
        public bool HoldTickLrConsignor { get; set; }
        public bool HoldTickLrConsignee { get; set; }
        public string State { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
