//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactBook
    {
        public int RECORDKEY { get; set; }
        public string AadharNo { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Adrl4 { get; set; }
        public Nullable<System.DateTime> Anndate { get; set; }
        public Nullable<int> Area { get; set; }
        public string AssistEmail1 { get; set; }
        public string AssistEmail2 { get; set; }
        public string AssistMobile1 { get; set; }
        public string AssistMobile2 { get; set; }
        public string AssistName1 { get; set; }
        public string AssistName2 { get; set; }
        public string AssistTel1 { get; set; }
        public string AssistTel2 { get; set; }
        public bool AutoEmail { get; set; }
        public bool AutoSMS { get; set; }
        public Nullable<System.DateTime> Bdate { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> ChildBdate { get; set; }
        public string ChildName { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string CorrespondenceType { get; set; }
        public string Country { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> DftAddress { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Division { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string GSTNo { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> MailingCategory { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string PanNo { get; set; }
        public string Person { get; set; }
        public string PhotoPath { get; set; }
        public string Pin { get; set; }
        public Nullable<int> Religion { get; set; }
        public string Segment { get; set; }
        public Nullable<int> Sno { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> SpouseBdate { get; set; }
        public string SpouseName { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string UserID { get; set; }
        public string www { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
