//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int RECORDKEY { get; set; }
        public string AccountParentGroup { get; set; }
        public string AcHeadCode { get; set; }
        public string AcType { get; set; }
        public string AppBranch { get; set; }
        public bool ARAP { get; set; }
        public bool AutoEmail { get; set; }
        public bool AutoSMS { get; set; }
        public string BaseGr { get; set; }
        public bool BENumber { get; set; }
        public string Broker { get; set; }
        public Nullable<int> Category { get; set; }
        public bool CCBudget { get; set; }
        public bool CCReqd { get; set; }
        public string Code { get; set; }
        public string Collection { get; set; }
        public Nullable<int> CostCentre { get; set; }
        public string Delivery { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ENTEREDBY { get; set; }
        public bool ForceCC { get; set; }
        public string GroupTree { get; set; }
        public string Grp { get; set; }
        public bool Hide { get; set; }
        public bool IsPublic { get; set; }
        public bool IsSubLedger { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public Nullable<int> Level { get; set; }
        public string Name { get; set; }
        public bool NonActive { get; set; }
        public bool PartyChallan { get; set; }
        public bool PartyInvoice { get; set; }
        public Nullable<int> PCCode { get; set; }
        public bool PONumber { get; set; }
        public Nullable<int> SalesMan { get; set; }
        public string ShortName { get; set; }
        public string Designation { get; set; }
        public string UserID { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string ContractHitby { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Narr { get; set; }
    }
}
