//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyOT
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public string EmpID { get; set; }
        public int LocationCode { get; set; }
        public Nullable<System.DateTime> MonDate { get; set; }
        public string MonYr { get; set; }
        public string OnDay { get; set; }
        public Nullable<decimal> OTDays { get; set; }
        public Nullable<double> OTHours { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
