//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtorRecVouDetail
    {
        public int RecordKey { get; set; }
        public decimal Amount { get; set; }
        public string Branch { get; set; }
        public string TableKey { get; set; }
        public string ParentKey { get; set; }
        public string Type { get; set; }
        public string Prefix { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public decimal NetAmt { get; set; }
        public decimal TdsAmout { get; set; }
        public Nullable<decimal> Val1 { get; set; }
        public Nullable<decimal> Val2 { get; set; }
        public Nullable<decimal> Val3 { get; set; }
        public Nullable<decimal> Val4 { get; set; }
        public Nullable<decimal> Val5 { get; set; }
        public Nullable<decimal> Val6 { get; set; }
        public Nullable<decimal> Val7 { get; set; }
        public Nullable<decimal> Val8 { get; set; }
        public Nullable<decimal> Val9 { get; set; }
        public Nullable<decimal> Val10 { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string InvSrl { get; set; }
        public string InvType { get; set; }
        public int InvSno { get; set; }
        public string InvTableKey { get; set; }
        public string InvBranch { get; set; }
        public string InvPrefix { get; set; }
        public string Narr { get; set; }
        public bool AutoAdjInterface { get; set; }
    }
}
