//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelChallan
    {
        public int RECORDKEY { get; set; }
        public decimal Amt { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> ChlnDate { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public string DelyCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string InvNumber { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string Prefix { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> Salesman { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
