//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMaster
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> BillQty { get; set; }
        public string Branch { get; set; }
        public string Consignee { get; set; }
        public string Consigner { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryGoodStatus { get; set; }
        public int DeliveryNo { get; set; }
        public string DeliveryRemark { get; set; }
        public string DeliveryTime { get; set; }
        public string FromBranch { get; set; }
        public string GenerateType { get; set; }
        public string LoginBranch { get; set; }
        public int LrNO { get; set; }
        public string MobileNO { get; set; }
        public string ParentKey { get; set; }
        public string PersonName { get; set; }
        public bool POD { get; set; }
        public Nullable<System.DateTime> PODDate { get; set; }
        public string PODRemark { get; set; }
        public string PODTime { get; set; }
        public int Qty { get; set; }
        public Nullable<int> ShortQty { get; set; }
        public string TableKey { get; set; }
        public string ToBranch { get; set; }
        public string VehicleNO { get; set; }
        public double Weight { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Prefix { get; set; }
        public bool MultiDel { get; set; }
    }
}
