//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo
    {
        public string CompanyName { get; set; }
        public string CompanyPAN { get; set; }
        public string CompanyGST { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyContact { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyWebsite { get; set; }
        public string LedgerName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<decimal> Opening { get; set; }
        public string Branch { get; set; }
        public string Date { get; set; }
        public string Particulars { get; set; }
        public string Serial { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> BalanceField { get; set; }
        public string Reco { get; set; }
        public string Narration { get; set; }
    }
}
