//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepricRate
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> AssetYear { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> DoubleSLM { get; set; }
        public Nullable<decimal> DoubleWDV { get; set; }
        public Nullable<decimal> SingleSLM { get; set; }
        public Nullable<decimal> SingleWDV { get; set; }
        public string TagNo { get; set; }
        public Nullable<decimal> TripleSLM { get; set; }
        public Nullable<decimal> TripleWDV { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
