//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountMaster
    {
        public int RECORDKEY { get; set; }
        public bool AllowUserDisc { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AmountIs { get; set; }
        public bool AskAmount { get; set; }
        public Nullable<double> BuyQty { get; set; }
        public string Code { get; set; }
        public bool CombineDiscount { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> DiscLimit { get; set; }
        public string DiscountType { get; set; }
        public string DiscProduct { get; set; }
        public bool DiscProductLimit { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool Fri { get; set; }
        public Nullable<double> GetQty { get; set; }
        public string KOTDiscProduct { get; set; }
        public bool Mon { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Outlets { get; set; }
        public Nullable<decimal> PurchaseMin { get; set; }
        public bool QtyOption { get; set; }
        public Nullable<double> RequiredQty { get; set; }
        public bool Sat { get; set; }
        public string ServiceType { get; set; }
        public bool ShowDiscount { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public bool Sun { get; set; }
        public bool Thu { get; set; }
        public bool Tue { get; set; }
        public string UserList { get; set; }
        public bool Wed { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
