//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DlySchedule
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> AltAddress { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> Days { get; set; }
        public Nullable<int> DelySno { get; set; }
        public Nullable<System.DateTime> DlyDate { get; set; }
        public Nullable<decimal> ExecutedQty { get; set; }
        public Nullable<double> ExecutedQty2 { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public bool NotInStock { get; set; }
        public string ParentKey { get; set; }
        public string Prefix { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public double Qty2 { get; set; }
        public string RefNumber { get; set; }
        public Nullable<decimal> Reserved { get; set; }
        public string Sno { get; set; }
        public Nullable<int> Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
