//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocFormats
    {
        public int RECORDKEY { get; set; }
        public bool AttachDocs { get; set; }
        public string DocHandle { get; set; }
        public string EmailTemplate { get; set; }
        public string FormatCode { get; set; }
        public bool ItemAttach { get; set; }
        public string OutputDevice { get; set; }
        public bool Selected { get; set; }
        public bool SendEmail { get; set; }
        public Nullable<int> Sno { get; set; }
        public string StoredProc { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
