//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverMas
    {
        public int RECORDKEY { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string Guaranter { get; set; }
        public bool HoldDriver { get; set; }
        public Nullable<System.DateTime> HoldFrom { get; set; }
        public Nullable<System.DateTime> HoldTo { get; set; }
        public string LicenceNo { get; set; }
        public string LicencePath { get; set; }
        public Nullable<System.DateTime> LicExpDate { get; set; }
        public string MasCode { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string NAdd1 { get; set; }
        public string NAdd2 { get; set; }
        public string NAdd3 { get; set; }
        public string Name { get; set; }
        public string NCity { get; set; }
        public string NickName { get; set; }
        public string NPin { get; set; }
        public string NState { get; set; }
        public string PicturePath { get; set; }
        public string Pin { get; set; }
        public string Proof { get; set; }
        public string ProofNo { get; set; }
        public string Remark { get; set; }
        public bool ShowRemark { get; set; }
        public string State { get; set; }
        public string Tel { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
