//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverMaster
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string ENTEREDBY { get; set; }
        public string Guaranter { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public Nullable<System.DateTime> LicenceExpDate { get; set; }
        public string LicenceNo { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Posting { get; set; }
        public string ProofNo { get; set; }
        public bool Status { get; set; }
        public string ValidProof { get; set; }
        public string VehicleNo { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Ticklers { get; set; }
        public string HoldTicklers { get; set; }
        public string Reference { get; set; }
    }
}
