//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dztmp_zOS
    {
        public string RefDoc { get; set; }
        public string Branch { get; set; }
        public string ParentKey { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string Prefix { get; set; }
        public string Srl { get; set; }
        public int Sno { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Narr { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<int> CrPeriod { get; set; }
        public Nullable<int> MasterCrPeriod { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> oDueDays { get; set; }
        public string BillRemark { get; set; }
        public string BillThrough { get; set; }
        public System.DateTime BillSubDate { get; set; }
        public string OrdNumber { get; set; }
        public Nullable<System.DateTime> OrdDate { get; set; }
        public Nullable<decimal> Pending { get; set; }
        public Nullable<decimal> OnAccount { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> UnAdj { get; set; }
        public int Flag { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pin { get; set; }
        public string Country { get; set; }
        public string Person { get; set; }
        public Nullable<int> Category { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> SalesMan { get; set; }
        public string SalesManName { get; set; }
        public Nullable<int> Area { get; set; }
        public string AreaName { get; set; }
        public string Grp { get; set; }
        public string GrpName { get; set; }
        public int LocationCode { get; set; }
        public Nullable<int> Broker { get; set; }
        public string BrokerName { get; set; }
        public string Party { get; set; }
        public string Itemdetails { get; set; }
    }
}
