//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dztmp_zUnBillLR
    {
        public int LrNo { get; set; }
        public Nullable<int> oDueDays { get; set; }
        public decimal Amt { get; set; }
    }
}
