//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAllowDeduct
    {
        public int RECORDKEY { get; set; }
        public string AllowCode { get; set; }
        public bool AppESIC { get; set; }
        public bool AppESICfix { get; set; }
        public bool AppFPF { get; set; }
        public bool AppFPFfix { get; set; }
        public bool AppLWF { get; set; }
        public bool AppLWFFix { get; set; }
        public bool AppMisc { get; set; }
        public bool AppMiscFix { get; set; }
        public bool AppPF { get; set; }
        public bool AppPFfix { get; set; }
        public bool AppPT { get; set; }
        public bool AppPTfix { get; set; }
        public bool AppTDS { get; set; }
        public bool AppTDSfix { get; set; }
        public string Branch { get; set; }
        public string Category { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> CurrVal { get; set; }
        public string EmpID { get; set; }
        public string EqAmt { get; set; }
        public string Equation { get; set; }
        public string fld { get; set; }
        public Nullable<decimal> FldValue { get; set; }
        public string Head { get; set; }
        public string PostCode { get; set; }
        public string PostDCode { get; set; }
        public bool ToConsider { get; set; }
        public bool ToPrint { get; set; }
        public bool Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
