//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFamily
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string CprNumber { get; set; }
        public string EmpCode { get; set; }
        public string EmpID { get; set; }
        public Nullable<System.DateTime> FlyMemDOB { get; set; }
        public string FlyMemEmpAdd { get; set; }
        public string FlyMemEmployer { get; set; }
        public string FlyMemName { get; set; }
        public string FlyMemOcup { get; set; }
        public string FlyMemQual { get; set; }
        public string Relation { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
