//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpHoursSetup
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> CateNo { get; set; }
        public string EmpID { get; set; }
        public Nullable<decimal> FriFrom { get; set; }
        public Nullable<decimal> FriOT { get; set; }
        public Nullable<decimal> FriRate { get; set; }
        public Nullable<decimal> FriTo { get; set; }
        public Nullable<decimal> MonFrom { get; set; }
        public Nullable<decimal> MonOT { get; set; }
        public Nullable<decimal> MonRate { get; set; }
        public Nullable<decimal> MonTo { get; set; }
        public Nullable<decimal> SatFrom { get; set; }
        public Nullable<decimal> SatOT { get; set; }
        public Nullable<decimal> SatRate { get; set; }
        public Nullable<decimal> SatTo { get; set; }
        public Nullable<decimal> SunFrom { get; set; }
        public Nullable<decimal> SunOT { get; set; }
        public Nullable<decimal> SunRate { get; set; }
        public Nullable<decimal> SunTo { get; set; }
        public Nullable<decimal> ThuFrom { get; set; }
        public Nullable<decimal> ThuOT { get; set; }
        public Nullable<decimal> ThuRate { get; set; }
        public Nullable<decimal> ThuTo { get; set; }
        public Nullable<decimal> TueFrom { get; set; }
        public Nullable<decimal> TueOT { get; set; }
        public Nullable<decimal> TueRate { get; set; }
        public Nullable<decimal> TueTo { get; set; }
        public Nullable<decimal> WedFrom { get; set; }
        public Nullable<decimal> WedOT { get; set; }
        public Nullable<decimal> WedRate { get; set; }
        public Nullable<decimal> WedTo { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
