//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int RECORDKEY { get; set; }
        public string AadharNo { get; set; }
        public string AccNo { get; set; }
        public Nullable<int> AnnualBonus { get; set; }
        public string AppBranch { get; set; }
        public decimal Basic { get; set; }
        public string BasicType { get; set; }
        public string BkCode { get; set; }
        public int CateNo { get; set; }
        public string CitizenId { get; set; }
        public Nullable<System.DateTime> CPRExpiDt { get; set; }
        public Nullable<System.DateTime> CPRIssuDt { get; set; }
        public string CPRNo { get; set; }
        public Nullable<decimal> DaysPerPeriod { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Doc { get; set; }
        public Nullable<System.DateTime> Doi { get; set; }
        public System.DateTime Doj { get; set; }
        public Nullable<System.DateTime> Dol { get; set; }
        public Nullable<System.DateTime> Dor { get; set; }
        public string EmpCompId { get; set; }
        public int EmpGrade { get; set; }
        public string EmpID { get; set; }
        public Nullable<int> EmpType { get; set; }
        public Nullable<int> ESICAppl { get; set; }
        public string ESICNo { get; set; }
        public string ESICPostTo { get; set; }
        public Nullable<int> FPFAppl { get; set; }
        public bool FPFix { get; set; }
        public string FPFNo { get; set; }
        public string FPFPostTo { get; set; }
        public string GradeNo { get; set; }
        public Nullable<int> HolidayAppl { get; set; }
        public Nullable<decimal> HrsPerDay { get; set; }
        public string IFSC { get; set; }
        public string LeftReason { get; set; }
        public Nullable<decimal> LnOpen { get; set; }
        public Nullable<decimal> LoanOpen { get; set; }
        public Nullable<int> LWFappl { get; set; }
        public string LWFNo { get; set; }
        public string LWFPostTo { get; set; }
        public Nullable<decimal> MaxLoan { get; set; }
        public bool Monthly { get; set; }
        public bool MonthlyBasic { get; set; }
        public string Name { get; set; }
        public bool NonPension { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public string OTUnit { get; set; }
        public string PAN { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<int> PF { get; set; }
        public Nullable<decimal> PFAmt { get; set; }
        public Nullable<int> PfAppl { get; set; }
        public string PFCode { get; set; }
        public string PfNo { get; set; }
        public string PFPostTo { get; set; }
        public Nullable<int> PostNo { get; set; }
        public Nullable<int> PostNoJoin { get; set; }
        public int Prefix { get; set; }
        public Nullable<decimal> ProfAmt { get; set; }
        public Nullable<int> ProfAppl { get; set; }
        public string PTaxPostTo { get; set; }
        public string PTNo { get; set; }
        public Nullable<decimal> RateHour { get; set; }
        public int Shift { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> SumPresent { get; set; }
        public Nullable<int> TDSAppl { get; set; }
        public string TDSPostTo { get; set; }
        public Nullable<decimal> TotLoan { get; set; }
        public string UANNumber { get; set; }
        public Nullable<decimal> UnBasic { get; set; }
        public Nullable<System.DateTime> UpToDate { get; set; }
        public Nullable<decimal> WkDays { get; set; }
        public string WkHoli1 { get; set; }
        public string WkHoli2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
