//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        public int RECORDKEY { get; set; }
        public string AccNo { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public Nullable<int> AnnualBonus { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public string BasicType { get; set; }
        public string BkCode { get; set; }
        public string Branch { get; set; }
        public string CateNo { get; set; }
        public string CitizenId { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> ContExpiDt { get; set; }
        public Nullable<System.DateTime> ContIssuDt { get; set; }
        public string ContNo { get; set; }
        public string CountryNo { get; set; }
        public Nullable<System.DateTime> CPRExpiDt { get; set; }
        public Nullable<System.DateTime> CPRIssuDt { get; set; }
        public string CPRNo { get; set; }
        public Nullable<int> Dept { get; set; }
        public string Deptno { get; set; }
        public string District { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Doc { get; set; }
        public Nullable<System.DateTime> Doi { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public Nullable<System.DateTime> Dol { get; set; }
        public Nullable<System.DateTime> Dor { get; set; }
        public Nullable<System.DateTime> DrvLicExpiDt { get; set; }
        public Nullable<System.DateTime> DrvLicIssuDt { get; set; }
        public string DrvLicNo { get; set; }
        public string EduQuali { get; set; }
        public string Efname { get; set; }
        public string Email { get; set; }
        public string EmpCompId { get; set; }
        public string EmpGrade { get; set; }
        public string EmpID { get; set; }
        public Nullable<byte> EmpType { get; set; }
        public string Ename { get; set; }
        public Nullable<byte> EsicAppl { get; set; }
        public string EsicNo { get; set; }
        public string Esname { get; set; }
        public string Fax1 { get; set; }
        public Nullable<byte> FPFAppl { get; set; }
        public string FPFNo { get; set; }
        public string GradeNo { get; set; }
        public Nullable<int> HolidayAppl { get; set; }
        public string LeftReason { get; set; }
        public Nullable<decimal> LnOpen { get; set; }
        public Nullable<decimal> LoanOpen { get; set; }
        public Nullable<byte> LWFappl { get; set; }
        public string LWFNo { get; set; }
        public bool Married { get; set; }
        public Nullable<decimal> MaxLoan { get; set; }
        public bool Monthly { get; set; }
        public bool MonthlyBasic { get; set; }
        public string NAdd1 { get; set; }
        public string NAdd2 { get; set; }
        public string NAdd3 { get; set; }
        public string Name { get; set; }
        public string NCity { get; set; }
        public string NCountryNo { get; set; }
        public string NDistrict { get; set; }
        public string NFax1 { get; set; }
        public bool NonPension { get; set; }
        public string NPin { get; set; }
        public string NPostBox { get; set; }
        public string NState { get; set; }
        public string NTel1 { get; set; }
        public Nullable<double> OtRate { get; set; }
        public string OtUnit { get; set; }
        public string Pan { get; set; }
        public Nullable<System.DateTime> PassportExpiDt { get; set; }
        public Nullable<System.DateTime> PassportIssuDt { get; set; }
        public string PassPortNo { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<byte> PayMode { get; set; }
        public Nullable<System.DateTime> PermitExpiDt { get; set; }
        public Nullable<System.DateTime> PermitIssuDt { get; set; }
        public string PermitNo { get; set; }
        public Nullable<byte> PF { get; set; }
        public Nullable<byte> PfAppl { get; set; }
        public string pfcode { get; set; }
        public string PfNo { get; set; }
        public string Photo { get; set; }
        public string Pin { get; set; }
        public string PostBox { get; set; }
        public string PostNo { get; set; }
        public string PostNoJoin { get; set; }
        public Nullable<byte> Prefix { get; set; }
        public Nullable<double> ProfAmt { get; set; }
        public Nullable<byte> ProfAppl { get; set; }
        public string PTNo { get; set; }
        public Nullable<int> Religion { get; set; }
        public string ReligionNo { get; set; }
        public string Sex { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public string STDCode { get; set; }
        public Nullable<double> SumPresent { get; set; }
        public string Taluka { get; set; }
        public Nullable<byte> TDSAppl { get; set; }
        public string Tel1 { get; set; }
        public Nullable<decimal> TotLoan { get; set; }
        public bool Type { get; set; }
        public Nullable<decimal> UnBasic { get; set; }
        public Nullable<System.DateTime> UpToDate { get; set; }
        public Nullable<System.DateTime> VisaExpiDt { get; set; }
        public Nullable<System.DateTime> VisaIssuDt { get; set; }
        public string VisaNo { get; set; }
        public Nullable<byte> WkDays { get; set; }
        public string WkHoli1 { get; set; }
        public string WkHoli2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
