//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWBVehicleDetails
    {
        public long RECORDKEY { get; set; }
        public string Branch { get; set; }
        public System.DateTime Docdate { get; set; }
        public string EWBNO { get; set; }
        public string Description { get; set; }
        public string LRTablekey { get; set; }
        public string LCTablekey { get; set; }
        public string FMTablekey { get; set; }
        public System.DateTime ValidUpto { get; set; }
        public string ConsoleEWBNo { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
