//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpDet
    {
        public int RECORDKEY { get; set; }
        public string AdvLic { get; set; }
        public Nullable<int> AgentCode { get; set; }
        public string BankCertRefNo { get; set; }
        public string BankCode { get; set; }
        public Nullable<System.DateTime> BLDate { get; set; }
        public string BLNo { get; set; }
        public string Branch { get; set; }
        public bool ClaimRefund { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> Containers { get; set; }
        public string CountryDest { get; set; }
        public string CountryOrg { get; set; }
        public string CustomAuthNo { get; set; }
        public System.DateTime DateOfExport { get; set; }
        public Nullable<System.DateTime> DateOfRealisation { get; set; }
        public Nullable<System.DateTime> DateOfShip { get; set; }
        public Nullable<System.DateTime> DateOfShipBill { get; set; }
        public Nullable<int> DateOfShipBillAppl { get; set; }
        public string DescGoods { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<decimal> DrawBack { get; set; }
        public Nullable<int> DtOfExpAppl { get; set; }
        public string ExpAuthDesg { get; set; }
        public string ExpAuthName { get; set; }
        public string ExpAuthOffAddress { get; set; }
        public string ExpAuthResAddress { get; set; }
        public Nullable<decimal> FOB { get; set; }
        public Nullable<System.DateTime> GRDate { get; set; }
        public string GRNo { get; set; }
        public Nullable<double> GrossWt { get; set; }
        public Nullable<System.DateTime> GRPPDate { get; set; }
        public string GRPPNo { get; set; }
        public string GSTApp { get; set; }
        public Nullable<System.DateTime> GSTAppDate { get; set; }
        public Nullable<int> GSTEndorse { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public Nullable<decimal> MLFS { get; set; }
        public string ModeOfPack { get; set; }
        public string Narr { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<decimal> OtherIncentive { get; set; }
        public string ParentKey { get; set; }
        public string PlaceofRcpt { get; set; }
        public Nullable<int> PortDisch { get; set; }
        public string PortFinal { get; set; }
        public Nullable<int> PortLoad { get; set; }
        public Nullable<int> PreCarriageBy { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> SBDate { get; set; }
        public string SBNo { get; set; }
        public string ShipLine { get; set; }
        public string ShippMarks { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public Nullable<decimal> TareWt { get; set; }
        public string Terms { get; set; }
        public string Type { get; set; }
        public string VesselNo { get; set; }
        public string VoyageNo { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
