//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAsset
    {
        public int RECORDKEY { get; set; }
        public string AccountCode { get; set; }
        public string AccountGrp { get; set; }
        public Nullable<decimal> AccumDepr { get; set; }
        public Nullable<decimal> AccumDepr10 { get; set; }
        public Nullable<decimal> AccumDepr11 { get; set; }
        public Nullable<decimal> AccumDepr2 { get; set; }
        public Nullable<decimal> AccumDepr3 { get; set; }
        public Nullable<decimal> AccumDepr4 { get; set; }
        public Nullable<decimal> AccumDepr5 { get; set; }
        public Nullable<decimal> AccumDepr6 { get; set; }
        public Nullable<decimal> AccumDepr7 { get; set; }
        public Nullable<decimal> AccumDepr8 { get; set; }
        public Nullable<decimal> AccumDepr9 { get; set; }
        public string AcqType { get; set; }
        public string AgencyName { get; set; }
        public Nullable<System.DateTime> AMCFrom { get; set; }
        public Nullable<decimal> AMCRate { get; set; }
        public Nullable<System.DateTime> AMCTo { get; set; }
        public int AssetCategory { get; set; }
        public string AssetStatus { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public string Code { get; set; }
        public string CompreDet { get; set; }
        public bool Comprehensive { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CostCentre { get; set; }
        public string DeprAccount { get; set; }
        public bool Depreciable { get; set; }
        public Nullable<System.DateTime> DeprEndDt { get; set; }
        public string DeprMethod { get; set; }
        public Nullable<decimal> DeprRate { get; set; }
        public Nullable<decimal> DeprRateIT { get; set; }
        public bool DeprSinceInUse { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public bool FreeLabour { get; set; }
        public bool FreeParts { get; set; }
        public string InsuranceComp { get; set; }
        public Nullable<System.DateTime> LeaseFrom { get; set; }
        public Nullable<decimal> LeaseRate { get; set; }
        public Nullable<System.DateTime> LeaseTo { get; set; }
        public Nullable<System.DateTime> LicIssueDt { get; set; }
        public Nullable<double> LifeMonths { get; set; }
        public Nullable<decimal> MinCharges { get; set; }
        public string Name { get; set; }
        public string Narr { get; set; }
        public Nullable<decimal> NextDeprAmt { get; set; }
        public Nullable<System.DateTime> NextPremiumDue { get; set; }
        public bool OnSite { get; set; }
        public string ParentAsset { get; set; }
        public string ParentStatus { get; set; }
        public Nullable<int> Pickup { get; set; }
        public Nullable<System.DateTime> policyDate { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<decimal> PremiumAmt { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> PurchDate { get; set; }
        public string RegNo { get; set; }
        public string TagNo { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<decimal> ValueInsured { get; set; }
        public Nullable<System.DateTime> WarExpDate { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string WarrantyNote { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
