//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMMasterDraft
    {
        public int RECORDKEY { get; set; }
        public bool ActivityFollowup { get; set; }
        public Nullable<decimal> Adv { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Branch { get; set; }
        public string BroCode { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<decimal> ChgAmt1 { get; set; }
        public Nullable<decimal> ChgAmt10 { get; set; }
        public Nullable<decimal> ChgAmt2 { get; set; }
        public Nullable<decimal> ChgAmt3 { get; set; }
        public Nullable<decimal> ChgAmt4 { get; set; }
        public Nullable<decimal> ChgAmt5 { get; set; }
        public Nullable<decimal> ChgAmt6 { get; set; }
        public Nullable<decimal> ChgAmt7 { get; set; }
        public Nullable<decimal> ChgAmt8 { get; set; }
        public Nullable<decimal> ChgAmt9 { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CurrBranch { get; set; }
        public Nullable<int> CurrRoute { get; set; }
        public System.DateTime Date { get; set; }
        public string DraftName { get; set; }
        public string Driver { get; set; }
        public string ENTEREDBY { get; set; }
        public string FmNo { get; set; }
        public string FmStatus { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string FromBranch { get; set; }
        public Nullable<double> KM { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string LCno { get; set; }
        public Nullable<System.DateTime> LicenceExpDate { get; set; }
        public string LicenCeNo { get; set; }
        public string LoginBranch { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
        public Nullable<decimal> OldRate { get; set; }
        public bool Opening { get; set; }
        public string OwnerName { get; set; }
        public string ParentKey { get; set; }
        public string PayAt { get; set; }
        public Nullable<int> PayLoad { get; set; }
        public bool Payment { get; set; }
        public string ReceiptNo { get; set; }
        public string Remark { get; set; }
        public string RouteVia { get; set; }
        public string RouteViaName { get; set; }
        public bool ScheduleFollowup { get; set; }
        public bool ScheduleKMReq { get; set; }
        public bool ScheduleRequired { get; set; }
        public string SelectedRoute { get; set; }
        public bool status { get; set; }
        public string TableKey { get; set; }
        public Nullable<decimal> TDSAmt { get; set; }
        public string Time { get; set; }
        public string ToBranch { get; set; }
        public string TruckNo { get; set; }
        public string VehicleCategory { get; set; }
        public string VehicleStatus { get; set; }
        public string VehiclePostAc { get; set; }
        public string DriverPostAc { get; set; }
        public bool VehicleMaintainDriverAC { get; set; }
        public bool VehicleArAp { get; set; }
        public bool VehicleFmPostReq { get; set; }
        public decimal TotlExp { get; set; }
        public decimal TotlAdvExp { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
