//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMROUTETable
    {
        public int RECORDKEY { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> ArrivalKM { get; set; }
        public string ArrivalRemark { get; set; }
        public Nullable<System.DateTime> ArrivalReSchDate { get; set; }
        public Nullable<int> ArrivalReSchKm { get; set; }
        public string ArrivalReSchTime { get; set; }
        public Nullable<System.DateTime> ArrivalSchDate { get; set; }
        public Nullable<int> ArrivalSchKm { get; set; }
        public string ArrivalSchTime { get; set; }
        public string ArrivalTime { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> DispatchKM { get; set; }
        public string DispatchRemark { get; set; }
        public Nullable<System.DateTime> DispatchReSchDate { get; set; }
        public string DispatchReSchTime { get; set; }
        public Nullable<System.DateTime> DispatchSchDate { get; set; }
        public string DispatchSchTime { get; set; }
        public string DispatchTime { get; set; }
        public string ENTEREDBY { get; set; }
        public int FmNo { get; set; }
        public Nullable<int> Kilometers { get; set; }
        public string KilometersTime { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string LCNO { get; set; }
        public string Parent { get; set; }
        public bool RouteClear { get; set; }
        public string RouteType { get; set; }
        public string RouteVia { get; set; }
        public Nullable<int> SequenceRoute { get; set; }
        public int SubRoute { get; set; }
        public string UnLoadLCNO { get; set; }
        public string VehicleActivity { get; set; }
        public string VehicleNo { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Narr { get; set; }
        public string Deliveries { get; set; }
        public string Prefix { get; set; }
        public string Parentkey { get; set; }
        public string LODRefTablekey { get; set; }
        public string UNLODRefTablekey { get; set; }
        public string ConsignmentLoad { get; set; }
    }
}
