//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMSetup
    {
        public int RECORDKEY { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public bool ChgBroker { get; set; }
        public bool ChgDriver { get; set; }
        public bool ManualFMCheck { get; set; }
        public bool ContactNo { get; set; }
        public bool DeleteReq { get; set; }
        public int DeleteUptoHours { get; set; }
        public bool DriverName { get; set; }
        public bool EditReq { get; set; }
        public int EditUptoHours { get; set; }
        public string ENTEREDBY { get; set; }
        public bool FMBoth { get; set; }
        public bool FMGenerate { get; set; }
        public string FmType { get; set; }
        public bool ShowLedgerPost { get; set; }
        public bool KM { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public bool LicenceExpDate { get; set; }
        public bool LicenceNo { get; set; }
        public bool Payload { get; set; }
        public string VehicleCateStsMain { get; set; }
        public bool VehicleReadyStsOnly { get; set; }
        public bool VehiclesBranchWise { get; set; }
        public bool AttachARAP { get; set; }
        public bool AttachPostReq { get; set; }
        public string HireDrAc { get; set; }
        public bool ATDSAdjReq { get; set; }
        public bool HTDSAdjReq { get; set; }
        public bool OTDSAdjReq { get; set; }
        public bool AllowToChgTDS { get; set; }
        public string FooterDetails1 { get; set; }
        public string FooterDetails2 { get; set; }
        public string FooterDetails3 { get; set; }
        public string FooterDetails4 { get; set; }
        public bool GenerateSchedule { get; set; }
        public bool FillFromCurr { get; set; }
        public string DefaultPrint { get; set; }
        public bool ExcludeHire { get; set; }
        public bool CurrDatetOnlyreq { get; set; }
        public bool BackDateAllow { get; set; }
        public int BackDaysUpto { get; set; }
        public bool ForwardDateAllow { get; set; }
        public int ForwardDaysUpto { get; set; }
        public bool BranchwiseSrlReq { get; set; }
        public bool YearwiseSrlReq { get; set; }
        public bool CetralisedSrlReq { get; set; }
        public int Srl { get; set; }
        public bool FitnessExp { get; set; }
        public bool InsuranceExp { get; set; }
        public bool PUCExp { get; set; }
        public bool AIPExp { get; set; }
        public bool StateTaxExp { get; set; }
        public bool TPStateExp { get; set; }
        public bool GreenTaxExp { get; set; }
        public bool DriverExp { get; set; }
        public bool CetralisedManualSrlReq { get; set; }
        public bool YearwiseManualSrlReq { get; set; }
    }
}
