//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp
    {
        public int RECORDKEY { get; set; }
        public string Action { get; set; }
        public string Branch { get; set; }
        public string Communication { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> Dept { get; set; }
        public System.DateTime DocDate { get; set; }
        public int LocationCode { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string Party { get; set; }
        public string Person { get; set; }
        public string Prefix { get; set; }
        public string Remark { get; set; }
        public string Srl { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
