//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTLog
    {
        public int RECORDKEY { get; set; }
        public string Data { get; set; }
        public string Document { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Event { get; set; }
        public string GSTNo { get; set; }
        public string GSTUserID { get; set; }
        public string Status { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
