//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSNMaster
    {
        public int RECORDKEY { get; set; }
        public string CessIn { get; set; }
        public string CessOut { get; set; }
        public string CGSTIn { get; set; }
        public string CGSTOut { get; set; }
        public string Code { get; set; }
        public string Flag { get; set; }
        public int Grp { get; set; }
        public string IGSTIn { get; set; }
        public string IGSTOut { get; set; }
        public string Name { get; set; }
        public string Narr { get; set; }
        public string SGSTIn { get; set; }
        public string SGSTOut { get; set; }
        public string Unit { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
