//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSNRates
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Abatement { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public string Code { get; set; }
        public bool DiscOnTxbl { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public string Flag { get; set; }
        public Nullable<byte> GSTType { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public Nullable<decimal> RateLimit { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<int> Sno { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
