//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueQC
    {
        public int RECORDKEY { get; set; }
        public bool Agency { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public bool IssueforReTest { get; set; }
        public string IssueNoteNo { get; set; }
        public double IssueQty { get; set; }
        public int LocationCode { get; set; }
        public string Narr { get; set; }
        public string PartyCode { get; set; }
        public string Prefix { get; set; }
        public string ProductCode { get; set; }
        public string SerialNoQc { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public int Store { get; set; }
        public string TableKey { get; set; }
        public string TestType { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
