//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGroups
    {
        public int RECORDKEY { get; set; }
        public string AcCode { get; set; }
        public string AcCodeX { get; set; }
        public string AcType { get; set; }
        public string BaseGr { get; set; }
        public string Code { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string GroupTree { get; set; }
        public string Grp { get; set; }
        public Nullable<int> GrpKey { get; set; }
        public bool Hide { get; set; }
        public string HSNCode { get; set; }
        public bool IsDiscListApp { get; set; }
        public bool IsLast { get; set; }
        public bool IsPrefixCode { get; set; }
        public bool IsPrefixDescr { get; set; }
        public bool IsRateListApp { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> Level { get; set; }
        public string Name { get; set; }
        public bool NoAutoCode { get; set; }
        public string Prefix { get; set; }
        public Nullable<decimal> PurchDisc { get; set; }
        public Nullable<decimal> PurchPer { get; set; }
        public Nullable<double> PurchRate { get; set; }
        public string PurchTaxCode { get; set; }
        public Nullable<decimal> SalesDisc { get; set; }
        public Nullable<decimal> SalesMargin { get; set; }
        public Nullable<decimal> SalesMaxDisc { get; set; }
        public Nullable<decimal> SalesPer { get; set; }
        public Nullable<double> SalesRate { get; set; }
        public string SalesTaxCode { get; set; }
        public string Unit { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
