//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMore
    {
        public int RECORDKEY { get; set; }
        public string AllowedPack { get; set; }
        public string AltItem { get; set; }
        public Nullable<int> AssetCategory { get; set; }
        public byte[] BarcodeImage { get; set; }
        public Nullable<decimal> BatchSize { get; set; }
        public Nullable<int> CASNo { get; set; }
        public bool ChargesOnQty2 { get; set; }
        public string Class { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> Density { get; set; }
        public string DWGNumber { get; set; }
        public bool Flammable { get; set; }
        public string GenericCode { get; set; }
        public string GoodsHSN { get; set; }
        public Nullable<decimal> GRNProcTime { get; set; }
        public string GroupTree { get; set; }
        public Nullable<decimal> GrWeight { get; set; }
        public Nullable<decimal> GSIRate { get; set; }
        public Nullable<int> Hazard { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<int> iHeight { get; set; }
        public Nullable<int> iLength { get; set; }
        public string Incharge { get; set; }
        public Nullable<int> iWidth { get; set; }
        public Nullable<decimal> LCharges { get; set; }
        public byte[] Logo { get; set; }
        public string MatterState { get; set; }
        public Nullable<decimal> MaxLoad { get; set; }
        public Nullable<decimal> MCharges { get; set; }
        public string MfgLocation { get; set; }
        public bool MRPBase { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> OCharges { get; set; }
        public string PackingPlan { get; set; }
        public Nullable<decimal> PackingSize { get; set; }
        public Nullable<int> pHeight { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> pLength { get; set; }
        public Nullable<int> Potency { get; set; }
        public Nullable<decimal> PotencyAVG { get; set; }
        public string PUPrefix { get; set; }
        public Nullable<int> pWidth { get; set; }
        public byte[] QRCodeImage { get; set; }
        public string RouteCode { get; set; }
        public string StockistID { get; set; }
        public Nullable<decimal> Storage { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public string ThCode { get; set; }
        public string UnitDim { get; set; }
        public string UnitMaxLoad { get; set; }
        public string UnitWt { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
