//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemWarranty
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> AMCChgs { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> CallChgs { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public bool FreeLabour { get; set; }
        public bool FreeParts { get; set; }
        public Nullable<int> FreeService { get; set; }
        public int LocationCode { get; set; }
        public Nullable<decimal> MinCharges { get; set; }
        public bool OnSite { get; set; }
        public Nullable<int> Pickup { get; set; }
        public string Principle { get; set; }
        public string SCentreNo { get; set; }
        public bool ServiceCard { get; set; }
        public bool ServiceSch { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string WarrantyCover { get; set; }
        public string WarrantyNote { get; set; }
        public bool WarrantyPart { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
