//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public int RECORDKEY { get; set; }
        public string ABC { get; set; }
        public string AcCode { get; set; }
        public string AcCodeS { get; set; }
        public string AcCodeSX { get; set; }
        public string AcCodeX { get; set; }
        public bool AllowProdCat { get; set; }
        public bool AllowUser { get; set; }
        public bool AutoBatch { get; set; }
        public bool AutoBatchGRN { get; set; }
        public Nullable<int> AutoBatchIssue { get; set; }
        public bool AutoMFG { get; set; }
        public bool AutoSerialGRN { get; set; }
        public bool AutoSerialMFG { get; set; }
        public bool Availability { get; set; }
        public bool BatchAutoGRN { get; set; }
        public bool BatchCheckExp { get; set; }
        public Nullable<decimal> BatchDefExpDays { get; set; }
        public bool BatchExp { get; set; }
        public Nullable<decimal> BatchExpDays { get; set; }
        public bool BatchForce { get; set; }
        public bool BatchMFG { get; set; }
        public bool BatchNoDupl { get; set; }
        public string BatchPattern { get; set; }
        public bool BatchRates { get; set; }
        public bool BatchReq { get; set; }
        public Nullable<double> BatchSizeQty { get; set; }
        public Nullable<int> BatchWidth { get; set; }
        public Nullable<int> BINNumber { get; set; }
        public bool BINRequired { get; set; }
        public bool BOMReqd { get; set; }
        public string Branch { get; set; }
        public bool CanMfg { get; set; }
        public bool CanPurch { get; set; }
        public bool CanSale { get; set; }
        public bool CanSaleOnline { get; set; }
        public bool CanSubContract { get; set; }
        public bool ChargesOnQty2 { get; set; }
        public bool CheckMaxLevel { get; set; }
        public bool CheckMinLevel { get; set; }
        public bool CheckMRP { get; set; }
        public bool CheckPending2 { get; set; }
        public bool CheckReOrderLevel { get; set; }
        public bool CheckStock { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<double> CostRate { get; set; }
        public bool CostValue { get; set; }
        public Nullable<int> DCCode { get; set; }
        public Nullable<double> DefQty { get; set; }
        public Nullable<decimal> DeliverPrice { get; set; }
        public Nullable<int> DelyTime { get; set; }
        public Nullable<decimal> EOQ { get; set; }
        public Nullable<double> FIFORate { get; set; }
        public Nullable<decimal> FIFOValue { get; set; }
        public string FSN { get; set; }
        public Nullable<decimal> GRNLeadTime { get; set; }
        public string Grp { get; set; }
        public Nullable<decimal> HalfPrice { get; set; }
        public bool IsPartyDrugLic { get; set; }
        public bool IsPartyPoisonLic { get; set; }
        public Nullable<decimal> LastCostRate { get; set; }
        public Nullable<double> LastPurchRate { get; set; }
        public Nullable<decimal> LastValue { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public Nullable<double> LIFORate { get; set; }
        public Nullable<decimal> LIFOValue { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public int LocationCode { get; set; }
        public Nullable<double> MaxQty { get; set; }
        public Nullable<decimal> MfgLeadTime { get; set; }
        public string MfgLeadUnit { get; set; }
        public string MfgLocation { get; set; }
        public Nullable<double> MinDelyQty { get; set; }
        public Nullable<double> MinDlyQty { get; set; }
        public Nullable<double> MinQty { get; set; }
        public Nullable<double> MinSaleRate { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> MRPControlGroup { get; set; }
        public string MRPIPType { get; set; }
        public string MRPISType { get; set; }
        public bool MRPReqd { get; set; }
        public bool MRPTaxP { get; set; }
        public bool MRPTaxS { get; set; }
        public string MRPWOType { get; set; }
        public string Name { get; set; }
        public bool OverReserve { get; set; }
        public string Party { get; set; }
        public string PartyDrugLicNo { get; set; }
        public string PartyPoisonLicNo { get; set; }
        public Nullable<int> PCCode { get; set; }
        public string PGSTCode { get; set; }
        public Nullable<decimal> PointEarn { get; set; }
        public bool PortionPrice { get; set; }
        public Nullable<double> PQtyToleMinus { get; set; }
        public Nullable<double> PQtyTolePlus { get; set; }
        public Nullable<decimal> ProcLeadTime { get; set; }
        public Nullable<decimal> PurchDisc { get; set; }
        public Nullable<decimal> PurchDiscAmt { get; set; }
        public Nullable<int> PurchGroup { get; set; }
        public Nullable<decimal> PurchPer { get; set; }
        public Nullable<decimal> PurchRate { get; set; }
        public string PurchTaxCode { get; set; }
        public string PurchTaxOST { get; set; }
        public Nullable<decimal> QCLeadTime { get; set; }
        public bool QCReqd { get; set; }
        public bool QCReqdMfg { get; set; }
        public bool QCReqdOPT { get; set; }
        public bool QCReqdSub { get; set; }
        public Nullable<double> QCSampleQty { get; set; }
        public Nullable<double> QtyToleMinus { get; set; }
        public Nullable<double> QtyTolePlus { get; set; }
        public Nullable<double> QtyToleWO { get; set; }
        public Nullable<decimal> QuarterPrice { get; set; }
        public Nullable<int> RateMethod { get; set; }
        public bool RateOn2 { get; set; }
        public Nullable<decimal> RedemptionCost { get; set; }
        public Nullable<decimal> ReOrdDays { get; set; }
        public Nullable<decimal> ReOrdDaysC { get; set; }
        public bool ReOrdHighLow { get; set; }
        public Nullable<decimal> ReOrdLevel { get; set; }
        public Nullable<double> ReOrdQty { get; set; }
        public bool RestrictPR { get; set; }
        public Nullable<double> RetainQty { get; set; }
        public Nullable<decimal> ReTestPeriod { get; set; }
        public Nullable<double> ReTestQty { get; set; }
        public Nullable<decimal> SalesDisc { get; set; }
        public Nullable<decimal> SalesDiscAmt { get; set; }
        public Nullable<decimal> SalesMargin { get; set; }
        public Nullable<decimal> SalesMaxDisc { get; set; }
        public decimal SalesPer { get; set; }
        public Nullable<decimal> SalesRate { get; set; }
        public string SalesTaxCode { get; set; }
        public string SalesTaxOST { get; set; }
        public bool SecondUnit { get; set; }
        public bool SerialNoDupl { get; set; }
        public string SerialPatternGRN { get; set; }
        public string SerialPatternMFG { get; set; }
        public bool SerialPrefix { get; set; }
        public bool SerialReq { get; set; }
        public bool SerialType { get; set; }
        public string SGSTCode { get; set; }
        public bool SourceListReq { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<decimal> StockDays { get; set; }
        public bool StockReserve { get; set; }
        public bool StockSerial { get; set; }
        public int Store { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string UnitM { get; set; }
        public string UnitM2 { get; set; }
        public string UnitP { get; set; }
        public string UnitP2 { get; set; }
        public string UnitS { get; set; }
        public string UnitS2 { get; set; }
        public string VED { get; set; }
        public Nullable<System.DateTime> VerifyDate { get; set; }
        public Nullable<decimal> VerifyDays { get; set; }
        public bool VerifyItem { get; set; }
        public Nullable<decimal> WTRate { get; set; }
        public Nullable<decimal> WTValue { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
