//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int RECORDKEY { get; set; }
        public string BaseGr { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public string Posting { get; set; }
        public string GSTCode { get; set; }
        public string HSNCode { get; set; }
        public string AppBranch { get; set; }
        public bool StockMaintain { get; set; }
        public int ExpiryDays { get; set; }
        public int ExpiryKm { get; set; }
        public bool Active { get; set; }
        public string Narr { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
