//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCDetail
    {
        public int RECORDKEY { get; set; }
        public double ActWeight { get; set; }
        public int BalQty { get; set; }
        public string ChrgeType { get; set; }
        public double ChrWeight { get; set; }
        public string Consignee { get; set; }
        public string Consignor { get; set; }
        public System.DateTime Date { get; set; }
        public string DeliveryAt { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryModule { get; set; }
        public string DeliveryNo { get; set; }
        public string Description { get; set; }
        public string ENTEREDBY { get; set; }
        public string FromBranch { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public int LCno { get; set; }
        public double LRActWeight { get; set; }
        public string LRColln { get; set; }
        public string LRDelivery { get; set; }
        public int LRno { get; set; }
        public int LrQty { get; set; }
        public string LRRemark { get; set; }
        public string LrType { get; set; }
        public string ParentKey { get; set; }
        public string PickFrom { get; set; }
        public int Qty { get; set; }
        public string TableKey { get; set; }
        public string Time { get; set; }
        public string ToBranch { get; set; }
        public string Unit { get; set; }
        public int UnloadDirectQty { get; set; }
        public int UnloadGodwonQty { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Prefix { get; set; }
        public string LRRefTablekey { get; set; }
        public string LCRefTablekey { get; set; }
    }
}
