//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCMaster
    {
        public int RECORDKEY { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string Branch { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime Date { get; set; }
        public int DispachFM { get; set; }
        public string ENTEREDBY { get; set; }
        public string FromBranch { get; set; }
        public string GenerateType { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public int LCno { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public string LoadTime { get; set; }
        public string LoginBranch { get; set; }
        public string ParentKey { get; set; }
        public string Remark { get; set; }
        public string TableKey { get; set; }
        public string Time { get; set; }
        public string ToBranch { get; set; }
        public int TotalQty { get; set; }
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public string UnloadTime { get; set; }
        public string Prefix { get; set; }
        public string FMRefTablekey { get; set; }
    }
}
