//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCSetup
    {
        public int RECORDKEY { get; set; }
        public string AUTHIDS { get; set; }
        public bool ManualLcCheck { get; set; }
        public string AUTHORISE { get; set; }
        public bool DeleteReq { get; set; }
        public int DeleteUptoHours { get; set; }
        public bool EditReq { get; set; }
        public int EditUptoHours { get; set; }
        public bool CheckLrDate { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public bool LCBoth { get; set; }
        public bool LCGenerate { get; set; }
        public string FooterDetails1 { get; set; }
        public string FooterDetails2 { get; set; }
        public string FooterDetails3 { get; set; }
        public string FooterDetails4 { get; set; }
        public bool FillFromCurr { get; set; }
        public string DefaultPrint { get; set; }
        public bool CurrDatetOnlyreq { get; set; }
        public bool BackDateAllow { get; set; }
        public int BackDaysUpto { get; set; }
        public bool ForwardDateAllow { get; set; }
        public int ForwardDaysUpto { get; set; }
        public bool BranchwiseSrlReq { get; set; }
        public bool YearwiseSrlReq { get; set; }
        public bool CetralisedSrlReq { get; set; }
        public int Srl { get; set; }
        public bool CetralisedManualSrlReq { get; set; }
        public bool YearwiseManualSrlReq { get; set; }
    }
}
