//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDSsetup
    {
        public int RECORDKEY { get; set; }
        public int AfterLDSDate { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public bool AutoFreight { get; set; }
        public int AutoStartFrom { get; set; }
        public int BeforeLDSDate { get; set; }
        public Nullable<int> DaysList { get; set; }
        public int DeleteUptoHours { get; set; }
        public int EditUptoHours { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public bool LDSBoth { get; set; }
        public bool LDSDate { get; set; }
        public bool LDSGenerate { get; set; }
    }
}
