//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingConsignment
    {
        public int RECORDKEY { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string Branch { get; set; }
        public string RouteKey { get; set; }
        public string StockKey { get; set; }
        public int Qty { get; set; }
        public double Weight { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
