//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDet
    {
        public int RECORDKEY { get; set; }
        public string ApplNo { get; set; }
        public bool Deduct { get; set; }
        public Nullable<System.DateTime> Dot { get; set; }
        public Nullable<System.DateTime> DtIssue { get; set; }
        public string EmpID { get; set; }
        public Nullable<System.DateTime> FirstinstalDt { get; set; }
        public Nullable<decimal> InstalmentAmt { get; set; }
        public Nullable<double> Instalments { get; set; }
        public Nullable<decimal> InterestAmt { get; set; }
        public int LnCode { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public string LoanEntry { get; set; }
        public Nullable<decimal> OpenBal { get; set; }
        public bool Posted { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> TotLnBal { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
