//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRecover
    {
        public int RECORDKEY { get; set; }
        public decimal Amt { get; set; }
        public string Bank { get; set; }
        public string Code { get; set; }
        public string EmpID { get; set; }
        public int LnCode { get; set; }
        public bool Monthly { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Srl { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
