//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int RECORDKEY { get; set; }
        public string ApplNo { get; set; }
        public string BkCode { get; set; }
        public System.DateTime DateOfAppl { get; set; }
        public string EmpID { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<int> LoanType { get; set; }
        public Nullable<int> NoOfInst { get; set; }
        public string PaymentMode { get; set; }
        public bool Posted { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> Sanctioned { get; set; }
        public string SanctionedBy { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
