//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalDeliverySheet
    {
        public int RECORDKEY { get; set; }
        public Nullable<double> Advance { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public Nullable<double> Balalnce { get; set; }
        public string Branch { get; set; }
        public string ChallanNo { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime Date { get; set; }
        public string Driver { get; set; }
        public string ENTEREDBY { get; set; }
        public Nullable<double> Freight { get; set; }
        public string FromBranch { get; set; }
        public string GenerateType { get; set; }
        public Nullable<int> KM { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public int LDSNo { get; set; }
        public Nullable<System.DateTime> LicenceExpDate { get; set; }
        public string LicenceNo { get; set; }
        public string LoginBranch { get; set; }
        public string Owner { get; set; }
        public string ParentKey { get; set; }
        public string PayableAt { get; set; }
        public Nullable<int> PayLoad { get; set; }
        public string ReceiptNo { get; set; }
        public string Remark { get; set; }
        public string TableKey { get; set; }
        public string Time { get; set; }
        public string ToBranch { get; set; }
        public string VehicleCategory { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
    }
}
