//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalDeliveryRel
    {
        public int RECORDKEY { get; set; }
        public double Amount { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string ENTEREDBY { get; set; }
        public string ExpModule { get; set; }
        public string ExpType { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public int LDSNO { get; set; }
        public int LRno { get; set; }
        public string ParentKey { get; set; }
        public string PickType { get; set; }
        public int Qty { get; set; }
        public string TableKey { get; set; }
        public int UnloadQty { get; set; }
        public double UnloadWeight { get; set; }
        public double Weight { get; set; }
    }
}
