//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LorryReceiptExpenses
    {
        public int RECORDKEY { get; set; }
        public string ExpType { get; set; }
        public string DocNo { get; set; }
        public string LRno { get; set; }
        public double Qty { get; set; }
        public double Weight { get; set; }
        public decimal Amount { get; set; }
        public string ParentKey { get; set; }
        public string TableKey { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string ENTEREDBY { get; set; }
    }
}
