//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LRMaster
    {
        public int RECORDKEY { get; set; }
        public double ActWt { get; set; }
        public decimal Amt { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string BENumber { get; set; }
        public string BillBran { get; set; }
        public string BillingPartyInfo { get; set; }
        public string BillParty { get; set; }
        public System.DateTime BookDate { get; set; }
        public string Branch { get; set; }
        public string ChgType { get; set; }
        public double ChgWt { get; set; }
        public string Colln { get; set; }
        public string ConsigneeInfo { get; set; }
        public string ConsignerInfo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Crossing { get; set; }
        public Nullable<decimal> DecVal { get; set; }
        public string Delivery { get; set; }
        public string DescrType { get; set; }
        public string Dest { get; set; }
        public int DispachFM { get; set; }
        public int DispachLC { get; set; }
        public string DocNo { get; set; }
        public string ENTEREDBY { get; set; }
        public string EwayBill { get; set; }
        public string FormNo { get; set; }
        public string GstLiable { get; set; }
        public string GSTNO { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string LoginBranch { get; set; }
        public string LrGenerate { get; set; }
        public int LrNo { get; set; }
        public string LRtype { get; set; }
        public string Narr { get; set; }
        public int OtherBillQty { get; set; }
        public string ParentKey { get; set; }
        public string PartyInvoice { get; set; }
        public string PartyRef { get; set; }
        public string LRMode { get; set; }
        public bool POD { get; set; }
        public string PONumber { get; set; }
        public string Prefix { get; set; }
        public string RecCode { get; set; }
        public string SendCode { get; set; }
        public string ServiceType { get; set; }
        public string Source { get; set; }
        public string TableKey { get; set; }
        public string Time { get; set; }
        public int TotQty { get; set; }
        public string TransactionAt { get; set; }
        public string TrType { get; set; }
        public int UnbillQty { get; set; }
        public string UnitCode { get; set; }
        public decimal Val1 { get; set; }
        public decimal Val10 { get; set; }
        public decimal Val11 { get; set; }
        public decimal Val12 { get; set; }
        public decimal Val13 { get; set; }
        public decimal Val14 { get; set; }
        public decimal Val15 { get; set; }
        public decimal Val16 { get; set; }
        public decimal Val17 { get; set; }
        public decimal Val18 { get; set; }
        public decimal Val19 { get; set; }
        public decimal Val2 { get; set; }
        public decimal Val20 { get; set; }
        public decimal Val21 { get; set; }
        public decimal Val22 { get; set; }
        public decimal Val23 { get; set; }
        public decimal Val24 { get; set; }
        public decimal Val25 { get; set; }
        public decimal Val3 { get; set; }
        public decimal Val4 { get; set; }
        public decimal Val5 { get; set; }
        public decimal Val6 { get; set; }
        public decimal Val7 { get; set; }
        public decimal Val8 { get; set; }
        public decimal Val9 { get; set; }
        public string VehicleNo { get; set; }
        public string InfoName { get; set; }
        public string InfoContactNO { get; set; }
        public string InfoEmailId { get; set; }
        public string DieselLtr { get; set; }
        public decimal DieselAmt { get; set; }
        public string Driver { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string RateType { get; set; }
        public string RateChrgOn { get; set; }
        public Nullable<decimal> DriverTripExp { get; set; }
        public string HSNCODE { get; set; }
        public string TrnMode { get; set; }
        public string RecGST { get; set; }
        public string SendGST { get; set; }
        public string BillGST { get; set; }
        public string ConsignerAddNo { get; set; }
        public string ConsigneeAddNo { get; set; }
        public string BillPartyAddNo { get; set; }
        public Nullable<decimal> ActualExp { get; set; }
        public string ApprovedDiesel { get; set; }
        public string AdvanceDiesel { get; set; }
        public string TripNarr { get; set; }
        public string TripNo { get; set; }
        public string PendingDiesel { get; set; }
        public string StockAt { get; set; }
        public Nullable<System.DateTime> OrderReceivedDate { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
    }
}
