//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LRSetup
    {
        public int RECORDKEY { get; set; }
        public bool ManualLRCheck { get; set; }
        public string BillBranch { get; set; }
        public bool Charges { get; set; }
        public string ChrType { get; set; }
        public string Colln { get; set; }
        public bool ConsignerList { get; set; }
        public int DeclareValue { get; set; }
        public bool DeclareValueZero { get; set; }
        public string DefaultPaidCustomer { get; set; }
        public string DefaultToPayCustomer { get; set; }
        public string Del { get; set; }
        public bool DeleteReq { get; set; }
        public int DeleteUptoHours { get; set; }
        public bool EditReq { get; set; }
        public int EditUptoHours { get; set; }
        public bool EwayBill { get; set; }
        public bool GST { get; set; }
        public bool LRBoth { get; set; }
        public bool LRGenerate { get; set; }
        public string LRType { get; set; }
        public bool Paid { get; set; }
        public string PaidCustomer { get; set; }
        public bool ParticularFlag { get; set; }
        public bool PartyChallan { get; set; }
        public bool PartyInvoice { get; set; }
        public string ServiceType { get; set; }
        public bool Topay { get; set; }
        public string ToPayCustomer { get; set; }
        public string Unit { get; set; }
        public bool Vehicle { get; set; }
        public bool ActWeightReq { get; set; }
        public bool FetchContractbtn { get; set; }
        public bool FetchGeneralContrct { get; set; }
        public bool DispatchLREditReq { get; set; }
        public bool LRBillEditReq { get; set; }
        public string FooterDetails1 { get; set; }
        public string FooterDetails2 { get; set; }
        public string FooterDetails3 { get; set; }
        public string FooterDetails4 { get; set; }
        public Nullable<bool> FillFromCurr { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string GST_Ticklr { get; set; }
        public string EWB_Ticklr { get; set; }
        public string TrnMode { get; set; }
        public string DefaultPrint { get; set; }
        public bool CurrDatetOnlyreq { get; set; }
        public bool BackDateAllow { get; set; }
        public int BackDaysUpto { get; set; }
        public bool ForwardDateAllow { get; set; }
        public int ForwardDaysUpto { get; set; }
        public bool BranchwiseSrlReq { get; set; }
        public bool YearwiseSrlReq { get; set; }
        public bool CetralisedSrlReq { get; set; }
        public int Srl { get; set; }
        public string ExtraInfoTabAllowTo { get; set; }
        public int defaultQty { get; set; }
        public bool GetAutoTripNo { get; set; }
        public bool CetralisedManualSrlReq { get; set; }
        public bool YearwiseManualSrlReq { get; set; }
    }
}
