//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LWFMaster
    {
        public int RECORDKEY { get; set; }
        public string AccPeriod { get; set; }
        public string Branch { get; set; }
        public string EmployeeLWF { get; set; }
        public string EmployerLWF { get; set; }
        public string HighLWF { get; set; }
        public string LowLWF { get; set; }
        public string LWFCode { get; set; }
        public Nullable<System.DateTime> LWFDate { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
