//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailInfo
    {
        public int RECORDKEY { get; set; }
        public string FromUId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public Nullable<long> MsgId { get; set; }
        public string Status { get; set; }
        public string Subject { get; set; }
        public string ToUId { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
