//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterGroups
    {
        public int RECORDKEY { get; set; }
        public string AcType { get; set; }
        public string AliasPrefix { get; set; }
        public string BaseGr { get; set; }
        public string Code { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool ForceCC { get; set; }
        public string Grp { get; set; }
        public Nullable<int> GrpKey { get; set; }
        public bool Hide { get; set; }
        public bool IsLast { get; set; }
        public Nullable<int> Level { get; set; }
        public string Name { get; set; }
        public bool NoDetails { get; set; }
        public Nullable<int> PCCode { get; set; }
        public string Prefix { get; set; }
        public string RevGroup { get; set; }
        public string Sch { get; set; }
        public Nullable<int> Seq { get; set; }
        public string StructureCode { get; set; }
        public bool SystemCode { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
