//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCrLimit
    {
        public int RECORDKEY { get; set; }
        public bool CheckCRDays { get; set; }
        public bool CheckCRLimit { get; set; }
        public string Code { get; set; }
        public bool CRDaysWarn { get; set; }
        public Nullable<decimal> CrLimit { get; set; }
        public Nullable<decimal> CRLimitTole { get; set; }
        public bool CRLimitWarn { get; set; }
        public bool CRLimitWithPO { get; set; }
        public bool CRLimitWithTrx { get; set; }
        public bool EmailPartyAlert { get; set; }
        public bool MergeCrLimit { get; set; }
        public bool SMSPartyAlert { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
