//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterAlerts
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public bool EmailParty { get; set; }
        public bool EmailSalesman { get; set; }
        public string EmailTemplate { get; set; }
        public string EmailUsers { get; set; }
        public Nullable<decimal> FormDays { get; set; }
        public bool FormFri { get; set; }
        public bool FormMon { get; set; }
        public bool FormSat { get; set; }
        public bool FormSun { get; set; }
        public bool FormThu { get; set; }
        public bool FormTue { get; set; }
        public bool FormWed { get; set; }
        public Nullable<int> FreqForm { get; set; }
        public Nullable<int> FreqOS { get; set; }
        public Nullable<System.DateTime> LastSent { get; set; }
        public Nullable<decimal> nFormDays { get; set; }
        public Nullable<decimal> nOSDays { get; set; }
        public Nullable<decimal> OSDays { get; set; }
        public bool OSFri { get; set; }
        public bool OSMon { get; set; }
        public bool OSSat { get; set; }
        public bool OSSun { get; set; }
        public bool OSThu { get; set; }
        public bool OSTue { get; set; }
        public bool OSWed { get; set; }
        public bool SMSParty { get; set; }
        public bool SMSSalesman { get; set; }
        public string SMSTemplate { get; set; }
        public string SMSUsers { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
