//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRules
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string CompCode { get; set; }
        public string SmsBranch { get; set; }
        public bool SendSMS { get; set; }
        public string SMSTemp { get; set; }
        public string EmailBranch { get; set; }
        public bool EmailAdd { get; set; }
        public bool EmaiEdit { get; set; }
        public bool EmaiDelete { get; set; }
        public bool EmaiPrint { get; set; }
        public bool EmaiBackDated { get; set; }
        public string MsgBranch { get; set; }
        public bool MsgAdd { get; set; }
        public bool MsgEdit { get; set; }
        public bool MsgDelete { get; set; }
        public bool MsgPrint { get; set; }
        public bool MsgBackDated { get; set; }
        public Nullable<decimal> LimitAmount { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
