//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> Category { get; set; }
        public string Code { get; set; }
        public string FromIDs { get; set; }
        public Nullable<System.DateTime> mDate { get; set; }
        public string Message { get; set; }
        public bool MessageDelete { get; set; }
        public Nullable<int> MessageID { get; set; }
        public bool MessageRead { get; set; }
        public Nullable<System.DateTime> mTime { get; set; }
        public string Prefix { get; set; }
        public bool ReplyRequest { get; set; }
        public bool SendNow { get; set; }
        public string Srl { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
