//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyHourly
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string EmpID { get; set; }
        public Nullable<double> Late { get; set; }
        public Nullable<double> LateRt { get; set; }
        public Nullable<System.DateTime> Mondate { get; set; }
        public Nullable<double> OT1 { get; set; }
        public Nullable<double> OT1Rt { get; set; }
        public Nullable<double> OT2 { get; set; }
        public Nullable<double> OT2Rt { get; set; }
        public Nullable<double> Regular { get; set; }
        public Nullable<double> RegularRt { get; set; }
        public string SalType { get; set; }
        public Nullable<double> Under { get; set; }
        public Nullable<double> UnderRt { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
