//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly
    {
        public int RECORDKEY { get; set; }
        public string AccNo { get; set; }
        public Nullable<decimal> ALL1 { get; set; }
        public Nullable<decimal> ALL10 { get; set; }
        public Nullable<decimal> All2 { get; set; }
        public Nullable<decimal> All3 { get; set; }
        public Nullable<decimal> ALL4 { get; set; }
        public Nullable<decimal> ALL5 { get; set; }
        public Nullable<decimal> ALL6 { get; set; }
        public Nullable<decimal> ALL7 { get; set; }
        public Nullable<decimal> ALL8 { get; set; }
        public Nullable<decimal> ALL9 { get; set; }
        public Nullable<decimal> ALLAMT1 { get; set; }
        public Nullable<decimal> ALLAMT10 { get; set; }
        public Nullable<decimal> AllAmt2 { get; set; }
        public Nullable<decimal> AllAmt3 { get; set; }
        public Nullable<decimal> ALLAMT4 { get; set; }
        public Nullable<decimal> ALLAMT5 { get; set; }
        public Nullable<decimal> ALLAMT6 { get; set; }
        public Nullable<decimal> ALLAMT7 { get; set; }
        public Nullable<decimal> ALLAmt8 { get; set; }
        public Nullable<decimal> ALLAmt9 { get; set; }
        public Nullable<double> AssYear { get; set; }
        public Nullable<decimal> BalBF { get; set; }
        public Nullable<decimal> BalCF { get; set; }
        public Nullable<decimal> BankCharges { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public string BkCode { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> CalculateBasic { get; set; }
        public string Category { get; set; }
        public string Cheque { get; set; }
        public Nullable<System.DateTime> ChequeDt { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> DED1 { get; set; }
        public Nullable<decimal> Ded10 { get; set; }
        public Nullable<decimal> Ded2 { get; set; }
        public Nullable<decimal> Ded3 { get; set; }
        public Nullable<decimal> Ded4 { get; set; }
        public Nullable<decimal> Ded5 { get; set; }
        public Nullable<decimal> Ded6 { get; set; }
        public Nullable<decimal> Ded7 { get; set; }
        public Nullable<decimal> Ded8 { get; set; }
        public Nullable<decimal> Ded9 { get; set; }
        public Nullable<decimal> DedAmt1 { get; set; }
        public Nullable<decimal> DedAmt10 { get; set; }
        public Nullable<decimal> DedAmt2 { get; set; }
        public Nullable<decimal> DedAmt3 { get; set; }
        public Nullable<decimal> DedAmt4 { get; set; }
        public Nullable<decimal> DedAmt5 { get; set; }
        public Nullable<decimal> DedAmt6 { get; set; }
        public Nullable<decimal> DedAmt7 { get; set; }
        public Nullable<decimal> DedAmt8 { get; set; }
        public Nullable<decimal> DedAmt9 { get; set; }
        public string Dept { get; set; }
        public string EmpID { get; set; }
        public Nullable<byte> EmpType { get; set; }
        public Nullable<double> ESICComp { get; set; }
        public Nullable<double> ESICCompAmt { get; set; }
        public Nullable<double> EsicEmp { get; set; }
        public Nullable<double> ESICEmpAmt { get; set; }
        public Nullable<double> FPFAmtComp { get; set; }
        public Nullable<double> FPFAmtemp { get; set; }
        public Nullable<double> FPFComp { get; set; }
        public Nullable<double> FPFEmp { get; set; }
        public string Grade { get; set; }
        public Nullable<double> LateHr { get; set; }
        public Nullable<double> LateHrRt { get; set; }
        public string LnRecCode { get; set; }
        public Nullable<decimal> LoanInterest { get; set; }
        public int LocationCode { get; set; }
        public Nullable<double> LWFComp { get; set; }
        public Nullable<double> LWFEmp { get; set; }
        public Nullable<System.DateTime> MonDate { get; set; }
        public string Monthyr { get; set; }
        public Nullable<byte> MthNo { get; set; }
        public string Narr { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<double> OT1 { get; set; }
        public Nullable<double> OT1Rt { get; set; }
        public Nullable<double> OT2 { get; set; }
        public Nullable<double> OT2Rt { get; set; }
        public Nullable<double> OtherHr { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<byte> PayMode { get; set; }
        public Nullable<double> PfAmtComp { get; set; }
        public Nullable<double> PfAmtemp { get; set; }
        public Nullable<double> PFComp { get; set; }
        public Nullable<double> PFEmp { get; set; }
        public string Post { get; set; }
        public bool Posted { get; set; }
        public Nullable<byte> PresentDay { get; set; }
        public Nullable<double> ProfTax { get; set; }
        public Nullable<byte> PublicHoliday { get; set; }
        public Nullable<double> RegHr { get; set; }
        public Nullable<System.DateTime> SalDate { get; set; }
        public string SalType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartDt { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> TDSAmt { get; set; }
        public Nullable<decimal> TotalAllow { get; set; }
        public Nullable<decimal> TotalDays { get; set; }
        public Nullable<decimal> TotalDed { get; set; }
        public Nullable<decimal> TotLn { get; set; }
        public Nullable<decimal> TotLnBal { get; set; }
        public Nullable<double> TravelAmt { get; set; }
        public Nullable<byte> TravelDays { get; set; }
        public Nullable<double> TravelRate { get; set; }
        public Nullable<int> UnAbsent { get; set; }
        public Nullable<decimal> UnBasic { get; set; }
        public Nullable<double> UnderHr { get; set; }
        public Nullable<double> UnderHrRt { get; set; }
        public Nullable<decimal> UnPaid { get; set; }
        public string WorkCode { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
