//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int RECORDKEY { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string ActiveRemark { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledRemark { get; set; }
        public string CompCode { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string CompleteRemark { get; set; }
        public Nullable<System.DateTime> HOLDDate { get; set; }
        public string HoldRemark { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string ParentKey { get; set; }
        public string Party { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> ReadyDate { get; set; }
        public string ReadyRemark { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public string Status { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
