//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersStk
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> AddTax { get; set; }
        public decimal Amt { get; set; }
        public bool BlanketOrder { get; set; }
        public string BOMSrl { get; set; }
        public string Branch { get; set; }
        public Nullable<int> CatNo { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> ChgAmt1 { get; set; }
        public Nullable<decimal> ChgAmt2 { get; set; }
        public Nullable<decimal> ChgAmt3 { get; set; }
        public Nullable<decimal> ChgAmt4 { get; set; }
        public Nullable<decimal> ChgAmt5 { get; set; }
        public Nullable<decimal> ChgAmt6 { get; set; }
        public Nullable<decimal> ChgPer1 { get; set; }
        public Nullable<decimal> ChgPer2 { get; set; }
        public Nullable<decimal> ChgPer3 { get; set; }
        public Nullable<decimal> ChgPer4 { get; set; }
        public Nullable<decimal> ChgPer5 { get; set; }
        public Nullable<decimal> ChgPer6 { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<double> cRate { get; set; }
        public int CurrName { get; set; }
        public decimal CurrRate { get; set; }
        public Nullable<decimal> CVDAmt { get; set; }
        public Nullable<decimal> CVDCessAmt { get; set; }
        public Nullable<decimal> CVDExtra { get; set; }
        public Nullable<decimal> CVDSCessAmt { get; set; }
        public Nullable<int> DCCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate2 { get; set; }
        public Nullable<int> Dely { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public System.DateTime DocDate { get; set; }
        public string EnqKey { get; set; }
        public double Factor { get; set; }
        public bool FirstSno { get; set; }
        public bool FreeQty { get; set; }
        public bool FromSO { get; set; }
        public bool Fvalue { get; set; }
        public Nullable<int> GSTNoITC { get; set; }
        public Nullable<int> GSTType { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public string IndKey { get; set; }
        public string InvKey { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public string JobTypeCode { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public bool MRPDone { get; set; }
        public string Narr { get; set; }
        public Nullable<double> NewRate { get; set; }
        public Nullable<double> NewRateEntry { get; set; }
        public Nullable<double> NewRateLink { get; set; }
        public Nullable<double> OpQty { get; set; }
        public string OrdKey { get; set; }
        public string ParentKey { get; set; }
        public string Party { get; set; }
        public Nullable<int> PCCode { get; set; }
        public string PIKKey { get; set; }
        public string PlanKey { get; set; }
        public string Prefix { get; set; }
        public string PriceListDisc { get; set; }
        public string PriceListRate { get; set; }
        public Nullable<int> ProcessCode { get; set; }
        public string ProjCode { get; set; }
        public Nullable<int> ProjectStage { get; set; }
        public Nullable<int> ProjectUnit { get; set; }
        public string QtnKey { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public Nullable<decimal> QtyPlan { get; set; }
        public Nullable<double> Rate { get; set; }
        public string RateCalcType { get; set; }
        public Nullable<int> RateOn { get; set; }
        public decimal RatePer { get; set; }
        public string RateType { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public string RefNumber { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Reserved { get; set; }
        public Nullable<double> ReservedQty { get; set; }
        public Nullable<System.DateTime> RevDate { get; set; }
        public string RevNarr { get; set; }
        public string RevNo { get; set; }
        public string SchemeCode { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public string Status { get; set; }
        public int Store { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string WasteFlag { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public string WOKey { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
