//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyChgs
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amt1 { get; set; }
        public Nullable<decimal> Amt10 { get; set; }
        public Nullable<decimal> Amt2 { get; set; }
        public Nullable<decimal> Amt3 { get; set; }
        public Nullable<decimal> Amt4 { get; set; }
        public Nullable<decimal> Amt5 { get; set; }
        public Nullable<decimal> Amt6 { get; set; }
        public Nullable<decimal> Amt7 { get; set; }
        public Nullable<decimal> Amt8 { get; set; }
        public Nullable<decimal> Amt9 { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public string MainType { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
