//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFESIC
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> AdvanceSrl { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<double> ESICcomp { get; set; }
        public string EsicCompno { get; set; }
        public Nullable<double> EsicEmp { get; set; }
        public bool ESICFix { get; set; }
        public Nullable<decimal> ESICLow { get; set; }
        public Nullable<decimal> ESICMax { get; set; }
        public Nullable<double> FPFComp { get; set; }
        public string fpfcompno { get; set; }
        public Nullable<double> FPFEmp { get; set; }
        public bool FPFFix { get; set; }
        public Nullable<decimal> FPFMax { get; set; }
        public Nullable<decimal> FPFupLimit { get; set; }
        public Nullable<int> LateHalf { get; set; }
        public Nullable<int> LoanSrl { get; set; }
        public int LocationCode { get; set; }
        public Nullable<System.DateTime> LunchHrFrom { get; set; }
        public Nullable<System.DateTime> LunchHrTo { get; set; }
        public bool MatchIDs { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public Nullable<decimal> OTRate1 { get; set; }
        public Nullable<decimal> OTRate2 { get; set; }
        public Nullable<double> PFComp { get; set; }
        public string pfCompno { get; set; }
        public Nullable<int> PFCurrDec { get; set; }
        public Nullable<double> PFEmp { get; set; }
        public bool PFFix { get; set; }
        public Nullable<decimal> PFMax { get; set; }
        public Nullable<decimal> PFupLimit { get; set; }
        public string PostDESICEmployee { get; set; }
        public string PostDESICEmployer { get; set; }
        public string PostDFPFEmployee { get; set; }
        public string PostDFPFEmployer { get; set; }
        public string PostDLoan { get; set; }
        public string PostDLWF { get; set; }
        public string PostDPFEmployee { get; set; }
        public string PostDPFEmployer { get; set; }
        public string PostDPT { get; set; }
        public string PostDSalary { get; set; }
        public string PostDTDS { get; set; }
        public bool PostEmpESIC { get; set; }
        public bool PostEmpESICE { get; set; }
        public bool PostEmpFPF { get; set; }
        public bool PostEmpFPFE { get; set; }
        public bool PostEmpLoan { get; set; }
        public bool PostEmpLWF { get; set; }
        public bool PostEmpPF { get; set; }
        public bool PostEmpPFE { get; set; }
        public bool PostEmpPTax { get; set; }
        public bool PostEmpSalary { get; set; }
        public bool PostEmpTDS { get; set; }
        public string PostESICEmployee { get; set; }
        public string PostESICEmployer { get; set; }
        public string PostFPFEmployee { get; set; }
        public string PostFPFEmployer { get; set; }
        public string PostLoan { get; set; }
        public string PostLoanIntC { get; set; }
        public string PostLoanIntD { get; set; }
        public string PostLWF { get; set; }
        public string PostPFEmployee { get; set; }
        public string PostPFEmployer { get; set; }
        public string PostPT { get; set; }
        public string PostSalary { get; set; }
        public string PostTDS { get; set; }
        public bool RegPattern { get; set; }
        public Nullable<System.DateTime> SalaryDate { get; set; }
        public Nullable<int> SalCurrDec { get; set; }
        public Nullable<decimal> ToleHalfIn { get; set; }
        public Nullable<decimal> ToleHalfOut { get; set; }
        public Nullable<decimal> ToleranceIn { get; set; }
        public Nullable<decimal> ToleranceOut { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
