//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinCodeLoc
    {
        public int RECORDKEY { get; set; }
        public string CircleName { get; set; }
        public string CityCode { get; set; }
        public string District { get; set; }
        public string DivisionName { get; set; }
        public string Locality { get; set; }
        public string PinCode { get; set; }
        public string RegionName { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string Taluka { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
