//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PInvoiceRev
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> AddTax { get; set; }
        public Nullable<decimal> AddTax2 { get; set; }
        public Nullable<byte> AltAddress { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Amt1 { get; set; }
        public Nullable<decimal> Amt10 { get; set; }
        public Nullable<decimal> Amt2 { get; set; }
        public Nullable<decimal> Amt3 { get; set; }
        public Nullable<decimal> Amt4 { get; set; }
        public Nullable<decimal> Amt5 { get; set; }
        public Nullable<decimal> Amt6 { get; set; }
        public Nullable<decimal> Amt7 { get; set; }
        public Nullable<decimal> Amt8 { get; set; }
        public Nullable<decimal> Amt9 { get; set; }
        public Nullable<decimal> aSurcharge { get; set; }
        public Nullable<int> BillContact { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillNumber { get; set; }
        public bool BlanketOrder { get; set; }
        public string Branch { get; set; }
        public string Broker { get; set; }
        public string Brokerage { get; set; }
        public Nullable<decimal> BrokerAmt { get; set; }
        public Nullable<decimal> BrokerOn { get; set; }
        public string CallBranch { get; set; }
        public bool CallCenter { get; set; }
        public Nullable<int> Campaign { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public string Competitors { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CRMStage { get; set; }
        public Nullable<decimal> CrPeriod { get; set; }
        public decimal CurrAmount { get; set; }
        public string currName { get; set; }
        public Nullable<decimal> currRate { get; set; }
        public Nullable<System.DateTime> DateWon { get; set; }
        public Nullable<int> DCCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate2 { get; set; }
        public Nullable<byte> DelyAltAdd { get; set; }
        public string DelyCode { get; set; }
        public Nullable<int> DelyContact { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public string DlyAddress { get; set; }
        public string DlyArea { get; set; }
        public string DlyCity { get; set; }
        public string DlyCountry { get; set; }
        public string DlyPerson { get; set; }
        public string DlyPin { get; set; }
        public string DlyState { get; set; }
        public string DlyTel { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> ExcAmt { get; set; }
        public Nullable<int> GSTNoITC { get; set; }
        public Nullable<int> GSTType { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public string InchargeID { get; set; }
        public string IncoPlace { get; set; }
        public Nullable<int> IncoTerms { get; set; }
        public string InsuranceNo { get; set; }
        public string JobTypeCode { get; set; }
        public Nullable<System.DateTime> LastUpdateOn { get; set; }
        public string LCNo { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string MediaType { get; set; }
        public Nullable<decimal> MLSAmt { get; set; }
        public string MLSKey { get; set; }
        public Nullable<decimal> MLSRate { get; set; }
        public string Narr { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> PayTerms { get; set; }
        public Nullable<System.DateTime> pInvDate { get; set; }
        public string pInvNumber { get; set; }
        public string PlaceOfSupply { get; set; }
        public string prefix { get; set; }
        public string ProjCode { get; set; }
        public string PurposeFor { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public double Qty2 { get; set; }
        public Nullable<System.DateTime> RevDate { get; set; }
        public string RevNarr { get; set; }
        public string RevNo { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> SalemanAmt { get; set; }
        public Nullable<decimal> SalemanOn { get; set; }
        public Nullable<decimal> SalemanPer { get; set; }
        public string Salesman { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public string ShipFrom { get; set; }
        public string ShortNote { get; set; }
        public string SourceDoc { get; set; }
        public Nullable<int> srl { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<decimal> STAmt { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Staxable { get; set; }
        public Nullable<decimal> STCess { get; set; }
        public string STCode { get; set; }
        public Nullable<decimal> STSheCess { get; set; }
        public string SubType { get; set; }
        public Nullable<decimal> SurCharge { get; set; }
        public string TableKey { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TDSAble { get; set; }
        public Nullable<decimal> TDSAmt { get; set; }
        public Nullable<decimal> TDSCess { get; set; }
        public bool TDSFlag { get; set; }
        public string TDSReason { get; set; }
        public Nullable<decimal> TDSSchg { get; set; }
        public Nullable<decimal> TDSTax { get; set; }
        public string Type { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> Val1 { get; set; }
        public Nullable<decimal> Val10 { get; set; }
        public Nullable<decimal> Val2 { get; set; }
        public Nullable<decimal> Val3 { get; set; }
        public Nullable<decimal> Val4 { get; set; }
        public Nullable<decimal> Val5 { get; set; }
        public Nullable<decimal> Val6 { get; set; }
        public Nullable<decimal> Val7 { get; set; }
        public Nullable<decimal> Val8 { get; set; }
        public Nullable<decimal> Val9 { get; set; }
        public Nullable<int> ValidDys { get; set; }
        public string WONumber { get; set; }
        public string zQty { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
