//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public int RECORDKEY { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string City { get; set; }
        public int Code { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public string Pin { get; set; }
        public string PostDrawBackCr { get; set; }
        public string PostDrawBackDr { get; set; }
        public string PostMLFSCr { get; set; }
        public string PostMLFSDr { get; set; }
        public string PostOtherCr { get; set; }
        public string PostOtherDr { get; set; }
        public string State { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
