//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintFormats
    {
        public int RECORDKEY { get; set; }
        public bool AttachDocs { get; set; }
        public string Code { get; set; }
        public Nullable<int> Copies { get; set; }
        public Nullable<int> DocsPerPage { get; set; }
        public Nullable<int> DocsPrinted { get; set; }
        public string Email { get; set; }
        public Nullable<int> Offset { get; set; }
        public Nullable<int> OutputDevice { get; set; }
        public string OutputFile { get; set; }
        public bool OverRide { get; set; }
        public string PageOrient { get; set; }
        public Nullable<int> PaperSize { get; set; }
        public Nullable<int> PaperTray { get; set; }
        public bool PrintQuality { get; set; }
        public string Prn { get; set; }
        public Nullable<int> TotalDocs { get; set; }
        public string Type { get; set; }
        public string WorkStation { get; set; }
        public string ZoomIn { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
