//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatLink
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> CatNo { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int LocationCode { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<decimal> MRPDisc { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> SalesMargin { get; set; }
        public Nullable<decimal> SalesMaxDisc { get; set; }
        public bool Type { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
