//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTMaster
    {
        public int RECORDKEY { get; set; }
        public string AccPeriod { get; set; }
        public string Branch { get; set; }
        public int Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<decimal> FebAmt { get; set; }
        public Nullable<decimal> HighPf { get; set; }
        public Nullable<decimal> HighPT { get; set; }
        public int LocationCode { get; set; }
        public Nullable<decimal> LowPf { get; set; }
        public Nullable<decimal> LowPT { get; set; }
        public string PfCode { get; set; }
        public Nullable<double> ProfAmt { get; set; }
        public Nullable<decimal> PTAmt { get; set; }
        public string PTType { get; set; }
        public int Sno { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
