//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelateDataItem
    {
        public int RECORDKEY { get; set; }
        public string ProductGroup { get; set; }
        public string Item { get; set; }
        public decimal Cost { get; set; }
        public string Qty { get; set; }
        public decimal TotalAmout { get; set; }
        public string WarrantyKm { get; set; }
        public string CurrentKM { get; set; }
        public string DueKM { get; set; }
        public string WarrantyDays { get; set; }
        public string MFGDate { get; set; }
        public string InstallDate { get; set; }
        public string DueDate { get; set; }
        public string HSNCode { get; set; }
        public string Description { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string TableKey { get; set; }
        public string Parentkey { get; set; }
    }
}
