//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelateData
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Branch { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
        public string Value4 { get; set; }
        public string Value5 { get; set; }
        public string Value6 { get; set; }
        public string Value7 { get; set; }
        public string Value8 { get; set; }
        public string Char1 { get; set; }
        public string Char2 { get; set; }
        public string Code { get; set; }
        public string Combo1 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string LrId { get; set; }
        public string MainType { get; set; }
        public Nullable<decimal> Num1 { get; set; }
        public Nullable<decimal> Num2 { get; set; }
        public Nullable<decimal> Num3 { get; set; }
        public Nullable<decimal> Num4 { get; set; }
        public string Prefix { get; set; }
        public Nullable<byte> RelateTo { get; set; }
        public string Sno { get; set; }
        public Nullable<int> Srl { get; set; }
        public string SubType { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string ParentKey { get; set; }
        public string TableKey { get; set; }
        public string Narr { get; set; }
        public Nullable<byte> Byte1 { get; set; }
        public Nullable<byte> Byte2 { get; set; }
        public Nullable<byte> Byte3 { get; set; }
        public Nullable<byte> Byte4 { get; set; }
        public Nullable<byte> Byte5 { get; set; }
        public Nullable<byte> Byte6 { get; set; }
        public Nullable<byte> Byte7 { get; set; }
        public Nullable<byte> Byte8 { get; set; }
        public bool AmtType { get; set; }
        public bool ReqRelated { get; set; }
        public bool Status { get; set; }
        public bool Clear { get; set; }
        public bool GSTFlag { get; set; }
        public string GSTCode { get; set; }
        public decimal IGSTAmt { get; set; }
        public decimal IGSTRate { get; set; }
        public decimal CGSTAmt { get; set; }
        public decimal CGSTRate { get; set; }
        public decimal SGSTAmt { get; set; }
        public decimal SGSTRate { get; set; }
        public bool ItemReq { get; set; }
    }
}
