//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelFm
    {
        public int RecordKey { get; set; }
        public string Branch { get; set; }
        public decimal FmAmt { get; set; }
        public string FMNo { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string ParentKey { get; set; }
        public string TableKey { get; set; }
        public int SrNo { get; set; }
        public string FMID { get; set; }
        public string Prefix { get; set; }
        public string FMRefTablekey { get; set; }
    }
}
