//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSchedule
    {
        public int RECORDKEY { get; set; }
        public string AppBranch { get; set; }
        public string Code { get; set; }
        public bool Date1 { get; set; }
        public bool Date10 { get; set; }
        public bool Date11 { get; set; }
        public bool Date12 { get; set; }
        public bool Date13 { get; set; }
        public bool Date14 { get; set; }
        public bool Date15 { get; set; }
        public bool Date16 { get; set; }
        public bool Date17 { get; set; }
        public bool Date18 { get; set; }
        public bool Date19 { get; set; }
        public bool Date2 { get; set; }
        public bool Date20 { get; set; }
        public bool Date21 { get; set; }
        public bool Date22 { get; set; }
        public bool Date23 { get; set; }
        public bool Date24 { get; set; }
        public bool Date25 { get; set; }
        public bool Date26 { get; set; }
        public bool Date27 { get; set; }
        public bool Date28 { get; set; }
        public bool Date29 { get; set; }
        public bool Date3 { get; set; }
        public bool Date30 { get; set; }
        public bool Date31 { get; set; }
        public bool Date4 { get; set; }
        public bool Date5 { get; set; }
        public bool Date6 { get; set; }
        public bool Date7 { get; set; }
        public bool Date8 { get; set; }
        public bool Date9 { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public bool DateWise { get; set; }
        public bool DayWise { get; set; }
        public string Email { get; set; }
        public string EmailID { get; set; }
        public bool Fri { get; set; }
        public Nullable<decimal> FriTime { get; set; }
        public string Ids { get; set; }
        public string Mobile { get; set; }
        public bool Mon { get; set; }
        public Nullable<decimal> MonTime { get; set; }
        public string Msg { get; set; }
        public Nullable<decimal> nTime { get; set; }
        public bool Sat { get; set; }
        public Nullable<decimal> SatTime { get; set; }
        public bool SendEmail { get; set; }
        public bool SendSMS { get; set; }
        public bool Sun { get; set; }
        public Nullable<decimal> SunTime { get; set; }
        public bool Thu { get; set; }
        public Nullable<decimal> ThuTime { get; set; }
        public bool Tue { get; set; }
        public Nullable<decimal> TueTime { get; set; }
        public string UserID { get; set; }
        public bool Wed { get; set; }
        public Nullable<decimal> WedTime { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
