//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQuery
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string Columns { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string Heading { get; set; }
        public string Opr { get; set; }
        public string Parameters { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string URL { get; set; }
        public string UserID { get; set; }
        public string Val { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
