//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOTP
    {
        public int RECORDKEY { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> GenDate { get; set; }
        public bool IsActive { get; set; }
        public string Message { get; set; }
        public string Mode { get; set; }
        public string OptionName { get; set; }
        public Nullable<int> OTP { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public string UserID { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
