//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class s
    {
        public string PKEy { get; set; }
        public string Rkey { get; set; }
        public string PayKey { get; set; }
        public Nullable<long> RowNumber { get; set; }
        public Nullable<long> RowNumber1 { get; set; }
    }
}
