//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTaxDetails
    {
        public int RECORDKEY { get; set; }
        public Nullable<int> AltAddress { get; set; }
        public decimal Amt { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillNumber { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> CessAmt { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public string Code { get; set; }
        public string CurrName { get; set; }
        public double CurrRate { get; set; }
        public Nullable<double> CurrRateI { get; set; }
        public Nullable<byte> DealerType { get; set; }
        public Nullable<int> DelyAltAdd { get; set; }
        public string Delycode { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string GSTNo { get; set; }
        public Nullable<byte> GSTNoITC { get; set; }
        public Nullable<byte> GSTType { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public string ItemType { get; set; }
        public string LocationCode { get; set; }
        public string MainType { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public bool NotInStock { get; set; }
        public string OrdNumber { get; set; }
        public string Party { get; set; }
        public string Prefix { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public string Sno { get; set; }
        public Nullable<int> Srl { get; set; }
        public string SubType { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public string TaxCode { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
