//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMore
    {
        public int RECORDKEY { get; set; }
        public string AdvLic { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> Brokerage { get; set; }
        public Nullable<decimal> BrokerAmt { get; set; }
        public Nullable<decimal> BrokerOn { get; set; }
        public string Contact { get; set; }
        public string DeliverBy { get; set; }
        public System.DateTime DocDate { get; set; }
        public bool EWayBillRequired { get; set; }
        public Nullable<decimal> FinCardFee { get; set; }
        public Nullable<decimal> FinDBDAmt { get; set; }
        public Nullable<decimal> FinDBDPer { get; set; }
        public Nullable<decimal> FinDownPayment { get; set; }
        public Nullable<decimal> FinEmiAmt { get; set; }
        public Nullable<decimal> FinLoanAmt { get; set; }
        public Nullable<decimal> FinProcessFee { get; set; }
        public Nullable<decimal> FinSafeFee { get; set; }
        public Nullable<int> FinTenure { get; set; }
        public Nullable<decimal> FinTotalAmt { get; set; }
        public string IncoPlace { get; set; }
        public Nullable<int> IncoTerms { get; set; }
        public Nullable<double> InvoiceQty { get; set; }
        public string ITFKey { get; set; }
        public string LCNo { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string OrdNumber { get; set; }
        public Nullable<int> PayTerms { get; set; }
        public string Prefix { get; set; }
        public string ProjCode { get; set; }
        public string Reason { get; set; }
        public string ReceiveBy { get; set; }
        public string RefBy { get; set; }
        public string RefDoc { get; set; }
        public string Reference { get; set; }
        public string RefParty { get; set; }
        public Nullable<int> RefSno { get; set; }
        public Nullable<decimal> SalemanAmt { get; set; }
        public Nullable<decimal> SalemanOn { get; set; }
        public Nullable<decimal> SalemanPer { get; set; }
        public string SalePurchNumber { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<decimal> TDSAble { get; set; }
        public Nullable<decimal> TDSAmt { get; set; }
        public Nullable<decimal> TDSCess { get; set; }
        public bool TDSFlag { get; set; }
        public string TDSReason { get; set; }
        public Nullable<decimal> TDSSchg { get; set; }
        public Nullable<decimal> TDSTax { get; set; }
        public string Type { get; set; }
        public string UPIAccount { get; set; }
        public Nullable<decimal> UPIAmount { get; set; }
        public string UPINo { get; set; }
        public string WONumber { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
