//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        public int RECORDKEY { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string AppBranch { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int Category { get; set; }
        public string City { get; set; }
        public int Code { get; set; }
        public Nullable<decimal> Comm { get; set; }
        public string CorpID { get; set; }
        public string Country { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Email { get; set; }
        public string EmpID { get; set; }
        public string Flag { get; set; }
        public int Grp { get; set; }
        public int GrpKey { get; set; }
        public bool Hide { get; set; }
        public string InOutFlag { get; set; }
        public Nullable<int> Level { get; set; }
        public bool Locked { get; set; }
        public byte[] Logo { get; set; }
        public string LowerList { get; set; }
        public bool Member { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string Password { get; set; }
        public string Pin { get; set; }
        public string State { get; set; }
        public string Telephone { get; set; }
        public string UserID { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
