//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendReceBill
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocType { get; set; }
        public int NoOfBill { get; set; }
        public string FTBranch { get; set; }
        public string Remark { get; set; }
        public string ENTEREDBY { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
    }
}
