//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTaxMaster
    {
        public int RECORDKEY { get; set; }
        public string AccCode { get; set; }
        public string CategoryCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string STCessPost { get; set; }
        public string STRatePost { get; set; }
        public string STSheCessPost { get; set; }
        public string SubClause { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
