//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareSetup
    {
        public int RECORDKEY { get; set; }
        public bool LRExtra { get; set; }
        public bool LRAttachReq { get; set; }
        public bool FmExtra { get; set; }
        public bool FMAttachReq { get; set; }
        public bool BillExtra { get; set; }
        public bool BillAttachReq { get; set; }
        public bool Payment { get; set; }
        public bool PaymentAttachReq { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string LRFormat { get; set; }
        public string FMFormat { get; set; }
        public string BillFormat { get; set; }
        public string PaymentFormat { get; set; }
        public string CCEmail { get; set; }
    }
}
