//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSRules
    {
        public int RECORDKEY { get; set; }
        public string CompCode { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string PartyBranch { get; set; }
        public bool PartyEmail { get; set; }
        public string PartyEmailTemp { get; set; }
        public bool PartySMS { get; set; }
        public string PartySMSTemp { get; set; }
        public string UsersList { get; set; }
        public string UserBranch { get; set; }
        public bool UserEmail { get; set; }
        public bool UserSMS { get; set; }
        public bool UserMsg { get; set; }
        public bool CheckBlank { get; set; }
        public int LocationCode { get; set; }
        public string OtherContact { get; set; }
        public bool SendBroker { get; set; }
        public bool SendSalesman { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string PartyEmailAttachments { get; set; }
        public string UserEmailAttachments { get; set; }
    }
}
