//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSRulesDue
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public string EmailTempDue { get; set; }
        public int LocationCode { get; set; }
        public string OtherContact { get; set; }
        public bool SendBroker { get; set; }
        public bool SendEmail { get; set; }
        public bool SendSalesman { get; set; }
        public bool SendSMS { get; set; }
        public bool SendUser { get; set; }
        public string SMSTempDue { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
