//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockQC
    {
        public int RECORDKEY { get; set; }
        public decimal Amt { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public double Factor { get; set; }
        public string GINNumber { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string ParentKey { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> ProcessCode { get; set; }
        public Nullable<int> QCCode { get; set; }
        public bool QCDone { get; set; }
        public string QCNarr { get; set; }
        public Nullable<System.DateTime> QCTimeIn { get; set; }
        public Nullable<System.DateTime> QCTimeOut { get; set; }
        public Nullable<int> QCType { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public Nullable<int> QtySno { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Reason { get; set; }
        public Nullable<double> RejectQty { get; set; }
        public Nullable<int> RejStore { get; set; }
        public bool SelfCertified { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public Nullable<int> Stage { get; set; }
        public int Store { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string WONumber { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
