//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMore
    {
        public int RECORDKEY { get; set; }
        public Nullable<double> AcceptedQty { get; set; }
        public Nullable<int> AltAddress { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillNumber { get; set; }
        public string BOMSrl { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Broker { get; set; }
        public Nullable<int> CatNo { get; set; }
        public Nullable<System.DateTime> ChlnDate { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> DelyAltAdd { get; set; }
        public System.DateTime DocDate { get; set; }
        public double Factor { get; set; }
        public Nullable<decimal> FuelAmt { get; set; }
        public Nullable<decimal> FuelQty { get; set; }
        public Nullable<decimal> FuelRate { get; set; }
        public Nullable<decimal> IDisc { get; set; }
        public Nullable<decimal> IDiscAmt { get; set; }
        public Nullable<double> InvoiceQty { get; set; }
        public Nullable<double> IRate { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public Nullable<decimal> LabourAmt { get; set; }
        public Nullable<decimal> LabourHrs { get; set; }
        public Nullable<decimal> LabourRate { get; set; }
        public int LocationCode { get; set; }
        public Nullable<decimal> MachineAmt { get; set; }
        public Nullable<decimal> MachineChgs { get; set; }
        public Nullable<int> MachineCode { get; set; }
        public Nullable<decimal> MachineRate { get; set; }
        public string MainType { get; set; }
        public Nullable<decimal> MCHrs { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<decimal> NoHrs { get; set; }
        public Nullable<System.DateTime> OrdDate { get; set; }
        public Nullable<decimal> OtherAmt { get; set; }
        public Nullable<decimal> OtherHrs { get; set; }
        public Nullable<decimal> OtherRate { get; set; }
        public string ParentKey { get; set; }
        public string Party { get; set; }
        public Nullable<decimal> PDisc { get; set; }
        public Nullable<decimal> PDiscAmt { get; set; }
        public Nullable<double> PRate { get; set; }
        public Nullable<decimal> PreDisc { get; set; }
        public Nullable<decimal> PreDiscAmt { get; set; }
        public string Prefix { get; set; }
        public Nullable<double> PreRate { get; set; }
        public string ProjCode { get; set; }
        public Nullable<double> QCQty { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public Nullable<decimal> RatePerHr { get; set; }
        public bool RateVerify { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public Nullable<int> ReasonType { get; set; }
        public Nullable<double> RejectedQty { get; set; }
        public Nullable<int> RejStore { get; set; }
        public Nullable<int> Shift { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string Unit2 { get; set; }
        public string WasteFlag { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
