//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBatch
    {
        public int RECORDKEY { get; set; }
        public string ARNumber { get; set; }
        public string Batch { get; set; }
        public string BatchParent { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<double> Factor { get; set; }
        public Nullable<decimal> GrWt { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<double> MRP { get; set; }
        public string Narr { get; set; }
        public Nullable<decimal> NettWt { get; set; }
        public Nullable<double> NewRate { get; set; }
        public bool NoExpiry { get; set; }
        public bool NotInStock { get; set; }
        public string ParentKey { get; set; }
        public string Party { get; set; }
        public Nullable<decimal> Potency { get; set; }
        public string Prefix { get; set; }
        public double Qty { get; set; }
        public double Qty2 { get; set; }
        public Nullable<double> Rate { get; set; }
        public string SerialNumber { get; set; }
        public string Shade { get; set; }
        public Nullable<int> Sno { get; set; }
        public string Srl { get; set; }
        public int SrNo { get; set; }
        public int Store { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string WONumber { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
