//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMinMax
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public bool CheckMaxLevel { get; set; }
        public bool CheckMinLevel { get; set; }
        public bool CheckMRP { get; set; }
        public bool CheckReOrderLevel { get; set; }
        public string Code { get; set; }
        public Nullable<int> DelyTime { get; set; }
        public System.DateTime EffDateFrom { get; set; }
        public System.DateTime EffDateTo { get; set; }
        public Nullable<decimal> EOQ { get; set; }
        public Nullable<decimal> GRNLeadTime { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public Nullable<double> MaxQty { get; set; }
        public Nullable<decimal> MfgLeadTime { get; set; }
        public string MfgLeadUnit { get; set; }
        public Nullable<double> MinDelyQty { get; set; }
        public Nullable<double> MinDlyQty { get; set; }
        public Nullable<double> MinQty { get; set; }
        public Nullable<decimal> ProcLeadTime { get; set; }
        public Nullable<decimal> ReOrdDays { get; set; }
        public Nullable<decimal> ReOrdDaysC { get; set; }
        public bool ReOrdHighLow { get; set; }
        public Nullable<decimal> ReOrdLevel { get; set; }
        public Nullable<double> ReOrdQty { get; set; }
        public Nullable<int> Store { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
