//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int RECORDKEY { get; set; }
        public bool Accepted { get; set; }
        public Nullable<System.DateTime> aEndDate { get; set; }
        public Nullable<System.DateTime> aEndTime { get; set; }
        public Nullable<int> aPeriod { get; set; }
        public string aPeriodString { get; set; }
        public string AssignedBy { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> aStartDate { get; set; }
        public Nullable<System.DateTime> aStartTime { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public int Code { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> DaysOfWeek { get; set; }
        public string Descr { get; set; }
        public System.DateTime DocDate { get; set; }
        public bool EmailReminder { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool Escalate { get; set; }
        public string EscalateTo { get; set; }
        public bool IsRecurring { get; set; }
        public Nullable<System.DateTime> LastSent { get; set; }
        public string Narr { get; set; }
        public bool nChoice { get; set; }
        public Nullable<int> nDays { get; set; }
        public Nullable<int> nListM1 { get; set; }
        public Nullable<int> nListM2 { get; set; }
        public Nullable<int> nListM3 { get; set; }
        public string Occurs { get; set; }
        public Nullable<int> PercentComplete { get; set; }
        public string Priority { get; set; }
        public bool ReadFlag { get; set; }
        public bool ReAssigned { get; set; }
        public Nullable<int> ReAssignedID { get; set; }
        public string RefDoc { get; set; }
        public string Reference { get; set; }
        public bool ReminderDone { get; set; }
        public bool ScreenReminder { get; set; }
        public bool SMSReminder { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Status { get; set; }
        public int TaskCode { get; set; }
        public bool Read { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public bool Reads { get; set; }
    }
}
