//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Abatement { get; set; }
        public Nullable<decimal> AddTax { get; set; }
        public string AddTaxCode { get; set; }
        public string ADescr { get; set; }
        public string ASchgCode { get; set; }
        public Nullable<decimal> ASurCharge { get; set; }
        public string Branch { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public string CessCode { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public string CGSTCode { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public string Code { get; set; }
        public bool Composition { get; set; }
        public bool DiscOnTxbl { get; set; }
        public bool Exempted { get; set; }
        public string Form { get; set; }
        public string FormName { get; set; }
        public Nullable<byte> GSTType { get; set; }
        public string IGSTCode { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public bool Inclusive { get; set; }
        public bool IsSERTax { get; set; }
        public bool Labour { get; set; }
        public bool Locked { get; set; }
        public bool MRPTax { get; set; }
        public string Name { get; set; }
        public bool NoCost { get; set; }
        public Nullable<decimal> Pct { get; set; }
        public string PostCode { get; set; }
        public string SchgCode { get; set; }
        public string Scope { get; set; }
        public Nullable<decimal> SetOff { get; set; }
        public string SGSTCode { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<decimal> SurCharge { get; set; }
        public bool Taxable { get; set; }
        public string TaxableCode { get; set; }
        public bool VATApp { get; set; }
        public bool VATGST { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
