//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSForm16
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public string EmpID { get; set; }
        public string FormType { get; set; }
        public string GridCode { get; set; }
        public int LocationCode { get; set; }
        public Nullable<decimal> Mth { get; set; }
        public Nullable<System.DateTime> PrdFrom { get; set; }
        public Nullable<System.DateTime> PrdTo { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public string TDSCircle { get; set; }
        public Nullable<decimal> TDSComp { get; set; }
        public Nullable<decimal> TDSOth { get; set; }
        public Nullable<decimal> Val1 { get; set; }
        public Nullable<decimal> Val10 { get; set; }
        public Nullable<decimal> Val12 { get; set; }
        public Nullable<decimal> Val13a { get; set; }
        public Nullable<decimal> Val13a2 { get; set; }
        public Nullable<decimal> Val13b { get; set; }
        public Nullable<decimal> Val13b2 { get; set; }
        public Nullable<decimal> Val13c { get; set; }
        public Nullable<decimal> Val16 { get; set; }
        public Nullable<decimal> Val17 { get; set; }
        public Nullable<decimal> Val1a { get; set; }
        public Nullable<decimal> Val1b { get; set; }
        public Nullable<decimal> Val1c { get; set; }
        public Nullable<decimal> Val2 { get; set; }
        public Nullable<decimal> Val2a { get; set; }
        public Nullable<decimal> Val2b { get; set; }
        public Nullable<decimal> Val3c { get; set; }
        public Nullable<decimal> Val4a { get; set; }
        public Nullable<decimal> Val4b { get; set; }
        public Nullable<decimal> Val4c { get; set; }
        public Nullable<decimal> Val7 { get; set; }
        public Nullable<decimal> Val7a { get; set; }
        public Nullable<decimal> Val7b { get; set; }
        public Nullable<decimal> Val7c { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
