//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSMaster
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public Nullable<int> CertAfter { get; set; }
        public bool CertAuto { get; set; }
        public Nullable<int> CertBefore { get; set; }
        public int Code { get; set; }
        public Nullable<int> DaysCert { get; set; }
        public Nullable<int> DaysDeposit { get; set; }
        public Nullable<int> DepositAfter { get; set; }
        public Nullable<int> DepositBefore { get; set; }
        public bool Differ { get; set; }
        public Nullable<int> FileAfter { get; set; }
        public Nullable<int> FileBefore { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string Form { get; set; }
        public bool Form15H { get; set; }
        public Nullable<byte> FormType { get; set; }
        public string Name { get; set; }
        public string PostCode { get; set; }
        public string Prefix { get; set; }
        public string Sections { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
