//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSPayments
    {
        public int RECORDKEY { get; set; }
        public string aMainType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string aPrefix { get; set; }
        public Nullable<int> aSno { get; set; }
        public string aSrl { get; set; }
        public string aSubType { get; set; }
        public string aType { get; set; }
        public string BankCode { get; set; }
        public string BillNumber { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
        public string CertNumber { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string ChallanNumber { get; set; }
        public string CNO { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public string DepositSerial { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool EndCredit { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string Narr { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public string ParentKey { get; set; }
        public string Party { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Prefix { get; set; }
        public int Sno { get; set; }
        public string Srl { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public Nullable<decimal> TDSAble { get; set; }
        public Nullable<decimal> TDSAmt { get; set; }
        public Nullable<decimal> TDSCess { get; set; }
        public Nullable<decimal> TDSCessAmt { get; set; }
        public Nullable<int> TDSCode { get; set; }
        public Nullable<int> TDSReason { get; set; }
        public Nullable<decimal> TDSSheCess { get; set; }
        public Nullable<decimal> TDSSheCessAmt { get; set; }
        public Nullable<decimal> TDSSurCharge { get; set; }
        public Nullable<decimal> TDSSurChargeAmt { get; set; }
        public Nullable<decimal> TDSTax { get; set; }
        public Nullable<decimal> TDSTaxAmt { get; set; }
        public Nullable<decimal> TotalTDSAmt { get; set; }
        public string Type { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
