//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSRates
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public int Code { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public Nullable<decimal> LimitFrom { get; set; }
        public Nullable<decimal> LimitTo { get; set; }
        public Nullable<decimal> SHECess { get; set; }
        public int Sno { get; set; }
        public Nullable<decimal> SurCharge { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TDSRate { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
