//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSReg
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string CompCode { get; set; }
        public int LocationCode { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> TDSDateFr { get; set; }
        public Nullable<System.DateTime> TDSDateTo { get; set; }
        public string TDSFormNo { get; set; }
        public string TDSQuarter { get; set; }
        public string TDSRegNo { get; set; }
        public Nullable<int> TDSSno { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
