//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSSetup
    {
        public int RECORDKEY { get; set; }
        public string AccPeriod { get; set; }
        public Nullable<int> AssFrom { get; set; }
        public Nullable<int> AssTo { get; set; }
        public string Branch { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Sec88AAmt { get; set; }
        public Nullable<decimal> Sec88Amt { get; set; }
        public Nullable<decimal> Sec88APct { get; set; }
        public Nullable<decimal> Sec88ARebate { get; set; }
        public Nullable<decimal> Sec88Pct { get; set; }
        public Nullable<decimal> Sec88Rebate { get; set; }
        public Nullable<decimal> Val { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
