//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempLRPODTable
    {
        public Nullable<int> LRno { get; set; }
        public Nullable<System.DateTime> LRCreateDate { get; set; }
        public Nullable<System.DateTime> LRBookDate { get; set; }
        public string LRSource { get; set; }
        public string LRDest { get; set; }
        public string LRRecCode { get; set; }
        public string LRSendCode { get; set; }
        public Nullable<int> PODNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PODDate { get; set; }
        public string Branch { get; set; }
        public string FromBranch { get; set; }
        public string ToBranch { get; set; }
        public string Task { get; set; }
        public string ModuleName { get; set; }
        public string ENTEREDBY { get; set; }
    }
}
