//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempPODReceivedLR
    {
        public string recordekey { get; set; }
        public System.DateTime Bookdate { get; set; }
        public string Branch { get; set; }
        public string ChrgeType { get; set; }
        public string Unit { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string LrType { get; set; }
        public string LRDelivery { get; set; }
        public string LRColln { get; set; }
        public int Lrno { get; set; }
        public string Authenticate { get; set; }
    }
}
