//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempAllGodownMultiStock
    {
        public string StockTablekey { get; set; }
        public string Tablekey { get; set; }
        public Nullable<int> LrNo { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string StockBranch { get; set; }
        public string StockType { get; set; }
        public Nullable<int> TotQty { get; set; }
        public Nullable<int> StockQty { get; set; }
        public Nullable<double> ActWt { get; set; }
        public Nullable<double> ChgWt { get; set; }
        public string ChgTypeName { get; set; }
        public string UnitName { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string ConsignerName { get; set; }
        public string ConsigneeName { get; set; }
        public string LRtypeName { get; set; }
        public string Delivery { get; set; }
        public string Colln { get; set; }
    }
}
