//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempExtEwayBillList
    {
        public string StockIN { get; set; }
        public string VehicleCode { get; set; }
        public string DocDate { get; set; }
        public string DocNo { get; set; }
        public string EWBNO { get; set; }
        public string LrTablekey { get; set; }
        public string StockAt { get; set; }
        public string Branch { get; set; }
        public Nullable<int> LrNo { get; set; }
        public string TableKey { get; set; }
        public int RECORDKEY { get; set; }
        public string Type { get; set; }
        public string TypeIN { get; set; }
        public Nullable<long> Rn { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string aPin { get; set; }
        public int StateCodeO { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public string Addrl1 { get; set; }
        public string Addrl2 { get; set; }
        public string Addrl3 { get; set; }
    }
}
