//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_TblBranchAllocation
    {
        public int RECORDKEY { get; set; }
        public string AUTHIDS { get; set; }
        public string AUTHORISE { get; set; }
        public string Branch { get; set; }
        public int Code { get; set; }
        public System.DateTime Date { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public int ManualFrom { get; set; }
        public int ManualTo { get; set; }
        public string TRN_Type { get; set; }
        public string Prefix { get; set; }
    }
}
