//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempEmergencyMail
    {
        public System.DateTime NextHitDate { get; set; }
        public System.DateTime UptoDate { get; set; }
        public string Particular { get; set; }
        public string Active { get; set; }
        public string DailyBasis { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public string Report { get; set; }
        public string FormatCode { get; set; }
        public string Account { get; set; }
    }
}
