//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfatEWB
    {
        public int RECORDKEY { get; set; }
        public string DocType { get; set; }
        public string Consignment { get; set; }
        public string DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocTime { get; set; }
        public string Prefix { get; set; }
        public string EWBNO { get; set; }
        public Nullable<System.DateTime> EWBValid { get; set; }
        public string VehicleNo { get; set; }
        public string EWBType { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Branch { get; set; }
        public string LrTablekey { get; set; }
        public string Narr { get; set; }
        public bool Clear { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string LREwaybill { get; set; }
        public string PartyInvoice { get; set; }
        public string BENUMBER { get; set; }
        public string GenMode { get; set; }
        public string ConsoleEWBList { get; set; }
    }
}
