//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatComp
    {
        public int RECORDKEY { get; set; }
        public string Adrl1 { get; set; }
        public string Adrl2 { get; set; }
        public string Adrl3 { get; set; }
        public string Adrl4 { get; set; }
        public string AssessOffice { get; set; }
        public Nullable<decimal> AuthCap { get; set; }
        public string AuthNo { get; set; }
        public string BankDetails { get; set; }
        public string Business { get; set; }
        public string CINNumber { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<byte> CompanyType { get; set; }
        public string CompID { get; set; }
        public string CompInfo { get; set; }
        public string Const { get; set; }
        public string Country { get; set; }
        public string cstno { get; set; }
        public string DDOCode { get; set; }
        public string DDOReg { get; set; }
        public string DeductorType { get; set; }
        public string fax { get; set; }
        public string GSTNo { get; set; }
        public string LastBranch { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string LastPeriod { get; set; }
        public string Licence1 { get; set; }
        public string Licence2 { get; set; }
        public byte[] Logo { get; set; }
        public string lstno { get; set; }
        public Nullable<int> Ministry { get; set; }
        public string Modules { get; set; }
        public string Name { get; set; }
        public string Nature { get; set; }
        public string PAN { get; set; }
        public string PAOCode { get; set; }
        public string PAOReg { get; set; }
        public bool PFFix { get; set; }
        public string PFupLimit { get; set; }
        public string Pin { get; set; }
        public string ServiceTaxNo { get; set; }
        public string SMSURL { get; set; }
        public string State { get; set; }
        public string STDCode { get; set; }
        public string Taluka { get; set; }
        public string TDSCir { get; set; }
        public string TDSReg { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string TINNo { get; set; }
        public string USERPass { get; set; }
        public string Users { get; set; }
        public string VATReg { get; set; }
        public string www { get; set; }
        public string Email { get; set; }
        public string BCCTo { get; set; }
        public string CCTo { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUser { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public bool GlobalMail { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string TransporteID { get; set; }
        public string SmsUername { get; set; }
        public string Smspassword { get; set; }
        public string SmsID { get; set; }
        public string SmsPara1 { get; set; }
        public string SmsPara2 { get; set; }
        public string SmsPara3 { get; set; }
        public string SmsPara4 { get; set; }
        public string SmsPara5 { get; set; }
        public string EwayEmail { get; set; }
        public string EwayUsername { get; set; }
        public string EwayPass { get; set; }
        public string EwayClientID { get; set; }
        public string EwayClientSecret { get; set; }
        public string EwayGSTIn { get; set; }
        public bool UseHSNMaster { get; set; }
        public string EInvoiceID { get; set; }
        public string EInvoicePassword { get; set; }
        public string EInvoiceGSTNo { get; set; }
        public string GSTAuthToken { get; set; }
        public Nullable<System.DateTime> GSTTokenExpiry { get; set; }
        public string GSTSEK { get; set; }
        public string CompEmail { get; set; }
    }
}
