//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatUserAudit
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> SancLimit { get; set; }
        public bool SendEmail { get; set; }
        public bool SendMSG { get; set; }
        public bool SendSMS { get; set; }
        public Nullable<int> Sno { get; set; }
        public string Type { get; set; }
        public string UserID { get; set; }
        public int UserLevel { get; set; }
        public string AppBranch { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
