//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfatNotificationSetup
    {
        public long RECORDKEY { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public bool Notification { get; set; }
        public bool Email { get; set; }
        public bool Priority { get; set; }
        public bool Self { get; set; }
        public bool Paramlistreq { get; set; }
        public string Param1 { get; set; }
        public bool Param2Req { get; set; }
        public decimal Param2 { get; set; }
        public string User { get; set; }
        public string Branch { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
