//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfatAutoOSMail
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public bool Customer { get; set; }
        public string Account { get; set; }
        public bool Active { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public string Time { get; set; }
        public bool EveryDay { get; set; }
        public bool Day { get; set; }
        public string DayName { get; set; }
        public bool DateR { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public bool SendMail { get; set; }
        public string Report { get; set; }
        public System.DateTime UptoDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime NextHitDate { get; set; }
    }
}
