//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfatNotification
    {
        public int RECORDKEY { get; set; }
        public string Srl { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string Branch { get; set; }
        public string prefix { get; set; }
        public bool Clear { get; set; }
        public bool Priority { get; set; }
        public string DocType { get; set; }
        public string DocNo { get; set; }
        public string Parentkey { get; set; }
        public string Tablekey { get; set; }
        public string Describe { get; set; }
        public string Msg { get; set; }
        public string HtmlString { get; set; }
        public string ToUser { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
