//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatUserRoles
    {
        public int RECORDKEY { get; set; }
        public string AccountRights { get; set; }
        public Nullable<byte> ActiveAssist { get; set; }
        public bool Animate { get; set; }
        public string Assistant { get; set; }
        public bool AuditTrail { get; set; }
        public bool BoldFont { get; set; }
        public bool ChangeForm { get; set; }
        public Nullable<byte> ColScheme { get; set; }
        public bool Control3D { get; set; }
        public bool DeskTop { get; set; }
        public string EmailID { get; set; }
        public bool EnterKey { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public bool FontBoldGrdC { get; set; }
        public bool FontBoldGrdH { get; set; }
        public bool FontBoldLbl { get; set; }
        public bool FontBoldTxt { get; set; }
        public string FontName { get; set; }
        public string FontNameGrdC { get; set; }
        public string FontNameGrdH { get; set; }
        public string FontNameLbl { get; set; }
        public string FontNameTxt { get; set; }
        public Nullable<byte> FontSize { get; set; }
        public Nullable<byte> FontSizeGrdC { get; set; }
        public Nullable<byte> FontSizeGrdH { get; set; }
        public Nullable<byte> FontSizeLbl { get; set; }
        public Nullable<byte> FontSizeTxt { get; set; }
        public bool ForceResize { get; set; }
        public bool FormCaption { get; set; }
        public bool Fri { get; set; }
        public bool HelpOnStart { get; set; }
        public bool Hide { get; set; }
        public string Ids { get; set; }
        public string LastBranch { get; set; }
        public string LastBranchUsed { get; set; }
        public string LastComp { get; set; }
        public string LastCompany { get; set; }
        public Nullable<System.DateTime> LastLastDt { get; set; }
        public Nullable<System.DateTime> LastStartDt { get; set; }
        public bool LastUser { get; set; }
        public bool Locked { get; set; }
        public string LogIns { get; set; }
        public bool Mon { get; set; }
        public string Name { get; set; }
        public Nullable<byte> OptionTab { get; set; }
        public string PassRead { get; set; }
        public string PassWords { get; set; }
        public string PrGroup { get; set; }
        public string ProductRights { get; set; }
        public bool RecMsg { get; set; }
        public bool RecSMS { get; set; }
        public bool Sat { get; set; }
        public string Signature { get; set; }
        public bool SoundEvent { get; set; }
        public bool StartRem { get; set; }
        public string StartUpForm { get; set; }
        public bool StartUpMemo { get; set; }
        public bool StatusBar { get; set; }
        public bool Sun { get; set; }
        public bool Thu { get; set; }
        public Nullable<byte> TipOnStart { get; set; }
        public Nullable<byte> ToolBar { get; set; }
        public Nullable<byte> ToolBarDisplay { get; set; }
        public bool Tue { get; set; }
        public string UserRole { get; set; }
        public string WallPaper { get; set; }
        public bool Wed { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
