//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatFormats
    {
        public int RECORDKEY { get; set; }
        public bool AttachDocs { get; set; }
        public bool AutoCharges { get; set; }
        public bool BarCodeFormat { get; set; }
        public bool BarCodePrinter { get; set; }
        public bool BarCodeQty { get; set; }
        public string BarCodeString { get; set; }
        public Nullable<int> BarCodeUps { get; set; }
        public Nullable<decimal> BarCodeWidth { get; set; }
        public string BarQtyEqsn { get; set; }
        public string BaseColProp { get; set; }
        public bool BaseEject { get; set; }
        public string BaseFilter { get; set; }
        public string BaseOrder { get; set; }
        public bool BaseProp { get; set; }
        public string BaseQuery { get; set; }
        public string BaseSummary { get; set; }
        public string BaseTable { get; set; }
        public string BeforeEach { get; set; }
        public Nullable<int> BottomMargin { get; set; }
        public Nullable<int> BoxIncrement { get; set; }
        public string Code { get; set; }
        public Nullable<int> Copies { get; set; }
        public string Dividers { get; set; }
        public string DocQuery { get; set; }
        public Nullable<int> DocsPerPage { get; set; }
        public string Email { get; set; }
        public string EmailTemplate { get; set; }
        public Nullable<long> FillColour { get; set; }
        public Nullable<long> FillColourW { get; set; }
        public bool FlexiBody { get; set; }
        public bool FontBold { get; set; }
        public bool FontItalics { get; set; }
        public string FontName { get; set; }
        public Nullable<byte> FontSize { get; set; }
        public bool FontStrike { get; set; }
        public bool FontUnderLine { get; set; }
        public bool FooterOnLast { get; set; }
        public string FormatStyle { get; set; }
        public bool Grid { get; set; }
        public bool GridExtend { get; set; }
        public Nullable<int> GridGap { get; set; }
        public bool GridHor { get; set; }
        public bool GridTotals { get; set; }
        public bool GridVer { get; set; }
        public bool GrpPrint { get; set; }
        public bool HeaderOnFirst { get; set; }
        public Nullable<int> Height { get; set; }
        public bool isFillBox { get; set; }
        public bool IsLastSel { get; set; }
        public string ISO { get; set; }
        public bool ItemEject { get; set; }
        public Nullable<decimal> LabelHorNos { get; set; }
        public Nullable<decimal> LabelHorSpace { get; set; }
        public bool LabelOption { get; set; }
        public Nullable<decimal> LabelVerNos { get; set; }
        public Nullable<decimal> LabelVerSpace { get; set; }
        public Nullable<byte> LastPagesPrinted { get; set; }
        public Nullable<int> LeftMargin { get; set; }
        public string Narr { get; set; }
        public Nullable<int> OutputDevice { get; set; }
        public string OutputFile { get; set; }
        public bool OverRide { get; set; }
        public bool PageOrient { get; set; }
        public Nullable<int> PaperSize { get; set; }
        public Nullable<int> PaperTray { get; set; }
        public bool PrintBodyLines { get; set; }
        public Nullable<decimal> PrintDelay { get; set; }
        public bool PrintQuality { get; set; }
        public string Prn { get; set; }
        public Nullable<int> RefreshInterval { get; set; }
        public string Remark { get; set; }
        public string RevisionBy { get; set; }
        public string RevNo { get; set; }
        public Nullable<int> RightMargin { get; set; }
        public bool RunAtStart { get; set; }
        public string Sections { get; set; }
        public string SubType { get; set; }
        public Nullable<int> TopMargin { get; set; }
        public Nullable<byte> Unit { get; set; }
        public string Users { get; set; }
        public string WaterMark { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<decimal> xCordChargesAmount { get; set; }
        public Nullable<decimal> xCordChargesHead { get; set; }
        public Nullable<int> ZoomIn { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
