//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatVehicleTrackingSetup
    {
        public int RECORDKEY { get; set; }
        public bool AllTime { get; set; }
        public int UptoDays { get; set; }
        public bool OnlySchedule { get; set; }
        public int ScheduleAndUptoDays { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public bool UptoDaysReq { get; set; }
        public bool ScheduleAndUptoDaysReq { get; set; }
        public bool VA_AllTime { get; set; }
        public bool VA_UptoDaysReq { get; set; }
        public int VA_UptoDays { get; set; }
        public bool VA_CompleteReq { get; set; }
        public bool CT_AllTime { get; set; }
        public bool CT_UptoDaysReq { get; set; }
        public int CT_UptoDays { get; set; }
        public bool CT_DeliveryReq { get; set; }
        public bool VM_AllTime { get; set; }
    }
}
