//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatForm
    {
        public int RECORDKEY { get; set; }
        public Nullable<byte> AutoIncr { get; set; }
        public bool AutoSize { get; set; }
        public string BackColor { get; set; }
        public bool BarCoded { get; set; }
        public bool Border { get; set; }
        public string Caption { get; set; }
        public bool Comma { get; set; }
        public string Cond { get; set; }
        public string ControlType { get; set; }
        public Nullable<byte> CPI { get; set; }
        public Nullable<byte> CPIStyle { get; set; }
        public Nullable<byte> DecS { get; set; }
        public string Equation { get; set; }
        public bool Fixed { get; set; }
        public string FldType { get; set; }
        public bool FontBold { get; set; }
        public bool FontItalics { get; set; }
        public string FontName { get; set; }
        public Nullable<byte> FontSize { get; set; }
        public bool FontStrike { get; set; }
        public bool FontUnderLine { get; set; }
        public string ForeColor { get; set; }
        public string Format { get; set; }
        public string FromRs { get; set; }
        public bool GroupHeader { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<byte> Justify { get; set; }
        public bool Locked { get; set; }
        public Nullable<byte> OnPage { get; set; }
        public Nullable<byte> PageJustify { get; set; }
        public bool PrintInHeader { get; set; }
        public Nullable<byte> Sections { get; set; }
        public bool SpaceSaver { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> WordWrapGap { get; set; }
        public bool WordWrapS { get; set; }
        public Nullable<int> X1 { get; set; }
        public Nullable<int> X2 { get; set; }
        public Nullable<int> Y1 { get; set; }
        public Nullable<int> Y2 { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
