//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatVehicleStatus
    {
        public int RECORDKEY { get; set; }
        public string DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Branch { get; set; }
        public string Status { get; set; }
        public string Vehicle { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Narr { get; set; }
        public System.DateTime EffDate { get; set; }
        public string EffTime { get; set; }
        public string refParentKey { get; set; }
    }
}
