//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatPass
    {
        public int RECORDKEY { get; set; }
        public bool AllowAlternate { get; set; }
        public bool AllowItem { get; set; }
        public bool AllowParty { get; set; }
        public string UserList { get; set; }
        public string AppBranch { get; set; }
        public string Assistant { get; set; }
        public string BCCTo { get; set; }
        public string CCTo { get; set; }
        public string Code { get; set; }
        public Nullable<int> ColScheme { get; set; }
        public string CompCode { get; set; }
        public string CorpID { get; set; }
        public bool DailyPassword { get; set; }
        public bool DashboardActive { get; set; }
        public Nullable<int> Dept { get; set; }
        public string DeviceID { get; set; }
        public bool DeviceStatus { get; set; }
        public bool DontChangePassword { get; set; }
        public string Email { get; set; }
        public string EmailClient { get; set; }
        public string EmailID { get; set; }
        public bool EmailVerified { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public bool Fri { get; set; }
        public Nullable<int> GridRows { get; set; }
        public string GUID { get; set; }
        public bool Hide { get; set; }
        public bool HideItemCode { get; set; }
        public bool HideItemName { get; set; }
        public bool IsHead { get; set; }
        public Nullable<int> Language { get; set; }
        public string LastBranch { get; set; }
        public string LastCompany { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastStartDt { get; set; }
        public string LicenseID { get; set; }
        public string LicNo { get; set; }
        public bool Locked { get; set; }
        public bool LoginNow { get; set; }
        public string LogIns { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> MinAcc { get; set; }
        public Nullable<int> MinItem { get; set; }
        public Nullable<int> MinOthers { get; set; }
        public string Mobile { get; set; }
        public bool MobileVerified { get; set; }
        public string Modules { get; set; }
        public bool Mon { get; set; }
        public Nullable<int> MsgDays { get; set; }
        public string Name { get; set; }
        public string PassRead { get; set; }
        public string PassWords { get; set; }
        public string Photograph { get; set; }
        public string POPServer { get; set; }
        public string Prefix { get; set; }
        public string PrGroup { get; set; }
        public bool PrintControl { get; set; }
        public bool RecMsg { get; set; }
        public bool RecSMS { get; set; }
        public bool Remember { get; set; }
        public bool Sat { get; set; }
        public string ServiceCentre { get; set; }
        public string Signature { get; set; }
        public bool SMTPNoSSL { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public bool SMTPRoute { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUser { get; set; }
        public string Status { get; set; }
        public string StrictIP { get; set; }
        public bool Sun { get; set; }
        public string TallySerial { get; set; }
        public string Telephone { get; set; }
        public string TfatURL { get; set; }
        public bool Thu { get; set; }
        public string TrackUsers { get; set; }
        public bool Tue { get; set; }
        public string UserLanguage { get; set; }
        public string UserRole { get; set; }
        public bool Wed { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string DefaultLoginBranch { get; set; }
        public string ConsignQryBranch { get; set; }
        public string FreightMemoQryBranch { get; set; }
        public string ConsignQryPanel { get; set; }
        public string FreightMemoQryPanel { get; set; }
    }
}
