//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatPeriods
    {
        public int RECORDKEY { get; set; }
        public string AccPeriod { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ClosedBy { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string OpenedBy { get; set; }
        public string PerdCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Status { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
