//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfatUserTask
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public bool TaskEmail { get; set; }
        public Nullable<int> TaskEndAfter { get; set; }
        public string TaskEndAfterType { get; set; }
        public Nullable<int> TaskRemEvery { get; set; }
        public string TaskRemEveryType { get; set; }
        public bool TaskScreen { get; set; }
        public bool TaskSMS { get; set; }
        public Nullable<int> TaskStartBefore { get; set; }
        public string TaskStartBeforeType { get; set; }
        public string TaskType { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
