//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpDriverLedgerDetails
    {
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Account { get; set; }
        public string Branch { get; set; }
        public string Type { get; set; }
        public string Serial { get; set; }
        public string BillNumber { get; set; }
        public string Particular { get; set; }
        public string ExpAc { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Narr { get; set; }
        public string ENTEREDBY { get; set; }
        public Nullable<long> RowNumber { get; set; }
    }
}
