//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripChargesMaRef
    {
        public int RECORDKEY { get; set; }
        public string DocNo { get; set; }
        public string FromBranch { get; set; }
        public string ToBranch { get; set; }
        public Nullable<decimal> TripCharge { get; set; }
        public Nullable<decimal> TripAdvance { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
