//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDetail
    {
        public int RECORDKEY { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string ChgCode { get; set; }
        public string Code { get; set; }
        public string Dest { get; set; }
        public string Narr { get; set; }
        public Nullable<int> Sno { get; set; }
        public string Source { get; set; }
        public string Vcode { get; set; }
        public string VType { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
