//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURDetail
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string DelBranch { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string DelTime { get; set; }
        public Nullable<double> DisQty { get; set; }
        public string LCNo { get; set; }
        public string LRNo { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> QtyRecd { get; set; }
        public string QtyStatus { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TURDate { get; set; }
        public string TURNo { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
