//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TyreStockTransfer
    {
        public int RECORDKEY { get; set; }
        public string DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Branch { get; set; }
        public string Parentkey { get; set; }
        public string Tablekey { get; set; }
        public string TransferToStock { get; set; }
        public string VehicleCode { get; set; }
        public string InstallFor { get; set; }
        public string TyrePlaceNo { get; set; }
        public string TyreSerialNo { get; set; }
        public System.DateTime InstallDate { get; set; }
        public string InstallKM { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Prefix { get; set; }
    }
}
