//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TyreMaster
    {
        public int RECORDKEY { get; set; }
        public bool Active { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Days { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> ExpiryDays { get; set; }
        public Nullable<double> KM { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string Name { get; set; }
        public bool opt { get; set; }
        public bool Type { get; set; }
        public string TyreType { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
