//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnLoadDetails
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string ChrgType { get; set; }
        public double ChrgWeight { get; set; }
        public string Coln { get; set; }
        public string Consignee { get; set; }
        public string Consigner { get; set; }
        public System.DateTime Date { get; set; }
        public string Delivery { get; set; }
        public string Description { get; set; }
        public int DQty { get; set; }
        public string ENTEREDBY { get; set; }
        public int FMNO { get; set; }
        public string FromBranch { get; set; }
        public int GQty { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public int LCNO { get; set; }
        public int LrNo { get; set; }
        public string LrType { get; set; }
        public string Remark { get; set; }
        public string Time { get; set; }
        public string ToBranch { get; set; }
        public string Unit { get; set; }
        public string VehicleNO { get; set; }
        public double Weight { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Prefix { get; set; }
        public string LRRefTablekey { get; set; }
        public string LCRefTablekey { get; set; }
        public string FMRefTablekey { get; set; }
    }
}
