//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public int RECORDKEY { get; set; }
        public string Code { get; set; }
        public bool Fri { get; set; }
        public bool Mon { get; set; }
        public string Name { get; set; }
        public bool Sat { get; set; }
        public bool Sun { get; set; }
        public bool Thu { get; set; }
        public bool Tue { get; set; }
        public bool Wed { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
