//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRightsTrx
    {
        public int RECORDKEY { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public int LocationCode { get; set; }
        public int Sno { get; set; }
        public string Type { get; set; }
        public bool xAdd { get; set; }
        public bool xBackDated { get; set; }
        public bool xCess { get; set; }
        public bool xDelete { get; set; }
        public bool xEdit { get; set; }
        public Nullable<decimal> xLimit { get; set; }
        public Nullable<decimal> xMinLimit { get; set; }
        public bool xPrint { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
