//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int RECORDKEY { get; set; }
        public string AllocToPerson { get; set; }
        public int Code { get; set; }
        public Nullable<System.DateTime> InsureDate { get; set; }
        public string Make { get; set; }
        public string Name { get; set; }
        public Nullable<long> PurchaseCost { get; set; }
        public Nullable<System.DateTime> Warranty { get; set; }
        public Nullable<System.DateTime> YearOfPurch { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
