//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verified
    {
        public int RECORDKEY { get; set; }
        public string Batch { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string CompCode { get; set; }
        public Nullable<double> CurrentStock { get; set; }
        public Nullable<decimal> DevAmt { get; set; }
        public Nullable<decimal> DevQty { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocTime { get; set; }
        public double Factor { get; set; }
        public int LocationCode { get; set; }
        public string MainType { get; set; }
        public string Narr { get; set; }
        public string ParentKey { get; set; }
        public string Prefix { get; set; }
        public Nullable<double> Qty { get; set; }
        public double Qty2 { get; set; }
        public string QtyEqsn { get; set; }
        public string Reason { get; set; }
        public string RegNumber { get; set; }
        public bool Selected { get; set; }
        public string SerialNumber { get; set; }
        public string Sno { get; set; }
        public Nullable<int> Srl { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<decimal> StkQty { get; set; }
        public Nullable<decimal> StkRate { get; set; }
        public Nullable<int> Store { get; set; }
        public string SubType { get; set; }
        public string TableKey { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string UserID { get; set; }
        public string WOKey { get; set; }
        public string xValue1 { get; set; }
        public string xValue2 { get; set; }
        public string YearCode { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
