//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalkinCustomer
    {
        public int RECORDKEY { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string Branch { get; set; }
        public string Code { get; set; }
        public string EmailId { get; set; }
        public string GSTNO { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Name { get; set; }
        public string PanNo { get; set; }
        public string Remark { get; set; }
        public bool Status { get; set; }
        public string Tickler { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
    }
}
