//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ztemp_PODReceivedFromBranch
    {
        public Nullable<long> rn { get; set; }
        public Nullable<int> PODNO { get; set; }
        public int Lrno { get; set; }
        public string LRTime { get; set; }
        public string LRDate { get; set; }
        public string ConsignerName { get; set; }
        public string ConsigneeName { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string Remark { get; set; }
        public string PODRefTablekey { get; set; }
        public string Authorise { get; set; }
        public string ConsignmentKey { get; set; }
        public string CurrentBranch { get; set; }
        public string SendReceive { get; set; }
        public string FromBranch { get; set; }
        public string ToBranch { get; set; }
    }
}
