//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_temp
    {
        public int IsLast { get; set; }
        public string grouptree { get; set; }
        public string C_Style { get; set; }
        public string MainGroup { get; set; }
        public string Flag { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public int Level { get; set; }
        public string Grp { get; set; }
        public decimal Opening { get; set; }
        public Nullable<decimal> dr { get; set; }
        public Nullable<decimal> cr { get; set; }
        public Nullable<decimal> bal { get; set; }
    }
}
