//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_BillReport
    {
        public string Tablekey { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string BillNumber { get; set; }
        public string GSTNo { get; set; }
        public string Customer { get; set; }
        public string AccountHead { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string Narr { get; set; }
        public Nullable<decimal> BillAmt { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public string Parentkey { get; set; }
        public string ReceivedFrom { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string ReceivedBranch { get; set; }
        public int Amount { get; set; }
        public int TdsAmout { get; set; }
        public int Val1 { get; set; }
        public int Val2 { get; set; }
        public int Val3 { get; set; }
        public int Val4 { get; set; }
        public int Val5 { get; set; }
        public int Val6 { get; set; }
        public int Val7 { get; set; }
        public int Val8 { get; set; }
        public int Val9 { get; set; }
        public int Val10 { get; set; }
        public int TotalReceivedAmount { get; set; }
        public string SBBranch { get; set; }
        public string SBDocNo { get; set; }
        public string SBType { get; set; }
        public string SBThrough { get; set; }
        public Nullable<System.DateTime> SBSubDt { get; set; }
        public string SBRemark { get; set; }
        public string SBENTEREDBY { get; set; }
        public Nullable<System.DateTime> SBLASTUPDATEDATE { get; set; }
    }
}
