//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_VehicleTripsheetReport
    {
        public System.DateTime DocDate { get; set; }
        public string DocNo { get; set; }
        public string Branch { get; set; }
        public string Driver { get; set; }
        public Nullable<decimal> TripCharges { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<decimal> KMExp { get; set; }
        public Nullable<decimal> OtherExp { get; set; }
        public Nullable<decimal> OtherDed { get; set; }
        public Nullable<decimal> CostCenter { get; set; }
        public int NetAmt { get; set; }
        public string FromKM { get; set; }
        public string ToKM { get; set; }
        public decimal PerKMChrg { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public decimal TDS { get; set; }
        public int DriveBal { get; set; }
        public Nullable<int> TotalDiesel { get; set; }
        public Nullable<decimal> UseDiesel { get; set; }
        public Nullable<decimal> ApprovedDiesel { get; set; }
        public string DocRef { get; set; }
    }
}
