//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_AutoMailData
    {
        public string Code { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Branch { get; set; }
        public string BillNumber { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> Pending { get; set; }
        public Nullable<decimal> OnAccount { get; set; }
        public Nullable<int> oDueDays { get; set; }
    }
}
