//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_LoadingDetails
    {
        public string Branch { get; set; }
        public string VehicleNO { get; set; }
        public Nullable<int> FMNO { get; set; }
        public string FMDate { get; set; }
        public int LCno { get; set; }
        public string LCDate { get; set; }
        public int LRno { get; set; }
        public int LrQty { get; set; }
        public double LRWeight { get; set; }
        public double LRActWeight { get; set; }
        public string Source { get; set; }
        public string Dest { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public System.DateTime BookDate { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
