//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_MailReports
    {
        public string Address { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string MsgText { get; set; }
        public string UserName { get; set; }
        public string ReportName { get; set; }
        public string PersonName { get; set; }
        public string Header { get; set; }
        public string AutoRemark { get; set; }
        public string BCC { get; set; }
        public string CC { get; set; }
        public string Account { get; set; }
    }
}
