//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmpmothlyUnbillLRStock_zOS1
    {
        public string TableKey { get; set; }
        public Nullable<int> LrNo { get; set; }
        public Nullable<int> oDueDays { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public string Branch { get; set; }
        public Nullable<int> TotQty { get; set; }
        public decimal DecVal { get; set; }
        public Nullable<double> ChgWt { get; set; }
        public Nullable<int> BalQty { get; set; }
    }
}
