//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_tfatEWB1
    {
        public string Actions { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Trans_DocNo { get; set; }
        public string GenMode { get; set; }
        public string LRRefTablekey { get; set; }
        public string EwayBilNo { get; set; }
        public string Valid_Upto { get; set; }
        public string Narr { get; set; }
        public string EnteredBy { get; set; }
        public string Sync_Branch { get; set; }
        public string ConsignmentNO { get; set; }
        public bool Clear { get; set; }
        public string StockBranchCode { get; set; }
        public string StockBranch { get; set; }
        public string Exact_Stock { get; set; }
        public Nullable<int> Stockkey { get; set; }
        public string Stock_At { get; set; }
        public string Stock_Type { get; set; }
        public Nullable<int> StockQty { get; set; }
        public string LR_EWB { get; set; }
        public string Party_Invoice { get; set; }
        public string BE_Number { get; set; }
        public string Book_Date { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string Vehicle { get; set; }
    }
}
