//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ztmp_EwayBillDetails3
    {
        public string EwayBilNo { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string StockBranchCode { get; set; }
        public Nullable<int> Stockkey { get; set; }
        public string StockType { get; set; }
        public Nullable<int> StockQty { get; set; }
    }
}
