//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_xTable
    {
        public string code { get; set; }
        public string name { get; set; }
        public string Grp { get; set; }
        public string xc1 { get; set; }
        public string xn1 { get; set; }
        public string xc2 { get; set; }
        public string xn2 { get; set; }
        public string xc3 { get; set; }
        public string xn3 { get; set; }
        public string xc4 { get; set; }
        public string xn4 { get; set; }
        public string xc5 { get; set; }
        public string xn5 { get; set; }
        public string xc6 { get; set; }
        public string xn6 { get; set; }
        public string xc7 { get; set; }
        public string xn7 { get; set; }
        public string xc8 { get; set; }
        public string xn8 { get; set; }
    }
}
