//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_LorryChallanReports
    {
        public string LCTablekey { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public string Time { get; set; }
        public Nullable<int> LCno { get; set; }
        public string LCFrom { get; set; }
        public string LCTo { get; set; }
        public Nullable<int> LCQty { get; set; }
        public string Remark { get; set; }
        public string USerName { get; set; }
        public string FMBranch { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int FmNo { get; set; }
        public string FMTablekey { get; set; }
        public string TruckNo { get; set; }
        public string Broker { get; set; }
        public string Driver { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PaidAt { get; set; }
        public string FMFrom { get; set; }
        public string RouteViaName { get; set; }
        public string FMTO { get; set; }
        public string LRBranch { get; set; }
        public int LrNo { get; set; }
        public string LRTablekey { get; set; }
        public System.DateTime LRDate { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string BillParty { get; set; }
        public string LRtype { get; set; }
        public string BillBranch { get; set; }
        public string Collection { get; set; }
        public string Delivery { get; set; }
        public int Qty { get; set; }
        public string Unit { get; set; }
        public int LRActWeight { get; set; }
        public int ChrWeight { get; set; }
        public string ChargeType { get; set; }
        public int Amt { get; set; }
        public string Description { get; set; }
        public string PartyChallan { get; set; }
        public string PartyInvoice { get; set; }
        public string PONumber { get; set; }
        public string BENumber { get; set; }
        public int DecVal { get; set; }
        public string GSTNO { get; set; }
        public string EwayBill { get; set; }
        public string LRMode { get; set; }
        public string ServiceType { get; set; }
        public string LRRemark { get; set; }
    }
}
