//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_TempLCMErgeTbl1
    {
        public Nullable<System.DateTime> ConsignmentDate { get; set; }
        public string Consignmentkey { get; set; }
        public string recordekey { get; set; }
        public string ChrgeType { get; set; }
        public string Unit { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string STKBranch { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string LrType { get; set; }
        public string LRDelivery { get; set; }
        public string LRColln { get; set; }
        public Nullable<int> Lrno { get; set; }
        public string EditLDSNo { get; set; }
        public string ShowAmountColumn { get; set; }
        public string ShowLoadQtyANdWeight { get; set; }
        public double ChrWeight { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PickType { get; set; }
        public int LoadGQty { get; set; }
        public int LoadDQty { get; set; }
        public Nullable<double> ActWeight { get; set; }
        public int LRActWeight { get; set; }
        public string Authenticate { get; set; }
        public System.DateTime LRDATESTK { get; set; }
        public string LRMode { get; set; }
    }
}
