//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_TfatDriverHistory
    {
        public System.DateTime LASTUPDATEDATE { get; set; }
        public System.DateTime FromPeriod { get; set; }
        public string FromTime { get; set; }
        public string TruckNo { get; set; }
        public Nullable<int> Days { get; set; }
        public string ENTEREDBY { get; set; }
        public string Narr { get; set; }
    }
}
