//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_ConsignmentReport
    {
        public string LRTablekey { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string LRVehicle { get; set; }
        public string Time { get; set; }
        public string Branch { get; set; }
        public Nullable<int> LrNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string BillParty { get; set; }
        public string LRtype { get; set; }
        public string BillBranch { get; set; }
        public string Collection { get; set; }
        public string Delivery { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<double> ActWt { get; set; }
        public Nullable<double> ChgWt { get; set; }
        public string ChargeType { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Description { get; set; }
        public string PartyChallan { get; set; }
        public string PartyInvoice { get; set; }
        public string PONumber { get; set; }
        public string BENumber { get; set; }
        public Nullable<decimal> DecVal { get; set; }
        public string GSTNO { get; set; }
        public string EwayBill { get; set; }
        public string LRMode { get; set; }
        public string ServiceType { get; set; }
        public string Remark { get; set; }
        public string UserName { get; set; }
        public string Status { get; set; }
        public string ALRTTablekey { get; set; }
        public string AlertNote { get; set; }
        public Nullable<System.DateTime> AlertNoteDate { get; set; }
        public string AlertNoteCreateBy { get; set; }
        public string OrderReceivedDate { get; set; }
        public string DateOfOrder { get; set; }
        public string ScheduleDate { get; set; }
        public string InfoName { get; set; }
        public int PLBill { get; set; }
        public int PLInAmt { get; set; }
        public int PLEXAmt { get; set; }
        public int TripAmt { get; set; }
        public Nullable<decimal> PLFMAmt { get; set; }
        public int PLADVBALFMAmt { get; set; }
        public string TAT { get; set; }
        public string LCTablekey { get; set; }
        public string LCBranch { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public Nullable<int> LCno { get; set; }
        public string LCFrom { get; set; }
        public string LCTo { get; set; }
        public Nullable<int> LCQty { get; set; }
        public string FMBranch { get; set; }
        public Nullable<System.DateTime> FMDate { get; set; }
        public Nullable<int> FMNo { get; set; }
        public decimal Freight { get; set; }
        public string FMDriver { get; set; }
        public string BroCode { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string FMTablekey { get; set; }
        public decimal FMF001 { get; set; }
        public decimal FMF002 { get; set; }
        public decimal FMF003 { get; set; }
        public decimal FMF004 { get; set; }
        public decimal FMF005 { get; set; }
        public decimal FMF006 { get; set; }
        public decimal FMF007 { get; set; }
        public decimal FMF008 { get; set; }
        public decimal FMF009 { get; set; }
        public decimal FMF010 { get; set; }
        public string FMPTablekey { get; set; }
        public int FMPF001 { get; set; }
        public int FMPF002 { get; set; }
        public int FMPF003 { get; set; }
        public int FMPF004 { get; set; }
        public int FMPF005 { get; set; }
        public int FMPF006 { get; set; }
        public int FMPF007 { get; set; }
        public int FMPF008 { get; set; }
        public int FMPF009 { get; set; }
        public int FMPF010 { get; set; }
        public string DelBranch { get; set; }
        public int DeliveryNo { get; set; }
        public string DELTablekey { get; set; }
        public System.DateTime DelDate { get; set; }
        public int DelQty { get; set; }
        public string BillType { get; set; }
        public string SaleBillBranch { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNumber { get; set; }
        public string SLRTablekey { get; set; }
        public int BillAmt { get; set; }
        public string SaleBillParty { get; set; }
        public int BillQty { get; set; }
        public string EXPTablekey { get; set; }
        public string ExpBranch { get; set; }
        public string ExpAccount { get; set; }
        public System.DateTime ExpDate { get; set; }
        public int ExpAmount { get; set; }
        public int IncAmount { get; set; }
        public string TripNo { get; set; }
        public string TripBranch { get; set; }
        public System.DateTime TripDate { get; set; }
        public string Driver { get; set; }
        public string VehicleFlag { get; set; }
        public int TripCharge { get; set; }
        public int LocalCharge { get; set; }
        public int ViaCharge { get; set; }
        public int TripTotal { get; set; }
        public string TripTablekey { get; set; }
    }
}
