//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_PickOrderReportDetails
    {
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public int OrderNo { get; set; }
        public string OrderFor { get; set; }
        public int TotQty { get; set; }
        public int BalQty { get; set; }
        public Nullable<double> ChgWt { get; set; }
        public string Branch { get; set; }
        public string InfoName { get; set; }
        public string InfoContactNO { get; set; }
        public string InfoEmailId { get; set; }
        public string ENTEREDBY { get; set; }
        public string LRBranch { get; set; }
        public int LrNo { get; set; }
        public int LRQty { get; set; }
        public System.DateTime LRBookDate { get; set; }
        public int LRWT { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string Source { get; set; }
        public string Dest { get; set; }
    }
}
