//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_FreightMemoReports
    {
        public string FMTablekey { get; set; }
        public System.DateTime Date { get; set; }
        public int FmNo { get; set; }
        public string Branch { get; set; }
        public string TruckNo { get; set; }
        public string Broker { get; set; }
        public string Driver { get; set; }
        public string Category { get; set; }
        public decimal Freight { get; set; }
        public decimal Advance { get; set; }
        public decimal Balance { get; set; }
        public string PaidAt { get; set; }
        public string From { get; set; }
        public string RouteViaName { get; set; }
        public string TO { get; set; }
        public int PLTotalLRBill { get; set; }
        public int PLBill { get; set; }
        public int LRINCAmt { get; set; }
        public int LREXPAmt { get; set; }
        public int FMINCAmt { get; set; }
        public int FMEXPAmt { get; set; }
        public int TripAmt { get; set; }
        public string LCBranch { get; set; }
        public System.DateTime LCDate { get; set; }
        public int LCno { get; set; }
        public string LCTablekey { get; set; }
        public string LCFrom { get; set; }
        public string LCTo { get; set; }
        public int LCQty { get; set; }
        public string LRBranch { get; set; }
        public int LrNo { get; set; }
        public string LRTablekey { get; set; }
        public System.DateTime LRDate { get; set; }
        public string LRFrom { get; set; }
        public string LRTo { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string BillParty { get; set; }
        public string LRtype { get; set; }
        public string BillBranch { get; set; }
        public string Collection { get; set; }
        public string Delivery { get; set; }
        public int LRQty { get; set; }
        public string Unit { get; set; }
        public int ActWt { get; set; }
        public int ChgWt { get; set; }
        public string ChargeType { get; set; }
        public string LREXPTablekey { get; set; }
        public string ExpBranch { get; set; }
        public string ExpAccount { get; set; }
        public System.DateTime ExpDate { get; set; }
        public int ExpAmount { get; set; }
        public int IncAmount { get; set; }
        public string FMEXPTablekey { get; set; }
        public string FMExpBranch { get; set; }
        public string FMExpAccount { get; set; }
        public System.DateTime FMExpDate { get; set; }
        public int FMExpAmount { get; set; }
        public int FMIncAmount { get; set; }
        public string VDTablekey { get; set; }
        public System.DateTime VouDate { get; set; }
        public string PayBranch { get; set; }
        public string Account { get; set; }
        public int NetAmt { get; set; }
        public string PaidOF { get; set; }
        public int AdvBal { get; set; }
        public int Bal { get; set; }
        public string TripNo { get; set; }
        public string TripBranch { get; set; }
        public System.DateTime TripDate { get; set; }
        public string TripDriver { get; set; }
        public string VehicleFlag { get; set; }
        public int TripCharge { get; set; }
        public int LocalCharge { get; set; }
        public int ViaCharge { get; set; }
        public int TripTotal { get; set; }
        public string TripTablekey { get; set; }
    }
}
