//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ztmp_TyreStockReport
    {
        public string BranndName { get; set; }
        public string SerialNo { get; set; }
        public string StockAt { get; set; }
        public string PLaceNO { get; set; }
        public string Status { get; set; }
    }
}
