using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ALT_ERP3.Areas.Accounts.Models
{
    public class TransactionClassificationVM
    {
        // iX9: Field Structure of DocTypes
        public int DocTypes_RECORDKEY { get; set; }
        public string DocTypes_AccountGroups { get; set; }
        public string DocTypes_AddCond { get; set; }
        public bool DocTypes_AddVatPurchase { get; set; }
        public int DocTypes_Agreement { get; set; }
        public bool DocTypes_AllowCurr { get; set; }
        public bool DocTypes_AllowDraftSave { get; set; }
        public bool DocTypes_AllowNeg { get; set; }
        public bool DocTypes_AllowOrdDupl { get; set; }
        public bool DocTypes_AllowStkAdjust { get; set; }
        public bool DocTypes_AllowTerms { get; set; }
        public bool DocTypes_AllowZero { get; set; }
        public string DocTypes_AppBranch { get; set; }
        public string DocTypes_AssCategory { get; set; }
        public bool DocTypes_AttachShow { get; set; }
        public bool DocTypes_AuditDetail { get; set; }
        public bool DocTypes_AuthReq { get; set; }
        public bool DocTypes_AutoChild { get; set; }
        public bool DocTypes_AutoGT { get; set; }
        public bool DocTypes_AutoGTEntry { get; set; }
        public bool DocTypes_AutoReserve { get; set; }
        public decimal DocTypes_BackDays { get; set; }
        public int DocTypes_BackHrs { get; set; }
        public bool DocTypes_BarCode { get; set; }
        public string DocTypes_BarCodeStruct { get; set; }
        public string DocTypes_BasedType { get; set; }
        public bool DocTypes_BatchReqd { get; set; }
        public bool DocTypes_BINRequired { get; set; }
        public bool DocTypes_BlanketOrder { get; set; }
        public string DocTypes_BMRFormat { get; set; }
        public string DocTypes_BPRFormat { get; set; }
        public string DocTypes_BRCFormat { get; set; }
        public bool DocTypes_BrokerCalculate { get; set; }
        public bool DocTypes_BrokerReqd { get; set; }
        public bool DocTypes_BudgetControl { get; set; }
        public string DocTypes_BudgetFlags { get; set; }
        public string DocTypes_BulkCond { get; set; }
        public bool DocTypes_CallCenter { get; set; }
        public string DocTypes_CashAcc { get; set; }
        public int DocTypes_Category { get; set; }
        public bool DocTypes_CatRates { get; set; }
        public bool DocTypes_CheckBillRef { get; set; }
        public string DocTypes_ChequeAcc { get; set; }
        public int DocTypes_Circulars { get; set; }
        public string DocTypes_COAFormat { get; set; }
        public string DocTypes_Code { get; set; }
        public bool DocTypes_CommonSeries { get; set; }
        public bool DocTypes_CommonSeriesCentralised { get; set; }
        public string DocTypes_CompCode { get; set; }
        public bool DocTypes_ConsigneeStock { get; set; }
        public string DocTypes_Constant { get; set; }
        public int DocTypes_ConstantMode { get; set; }
        public string DocTypes_CreditCardAcc { get; set; }
        public string DocTypes_CRFormat { get; set; }
        public string DocTypes_CurrConv { get; set; }
        public int DocTypes_CurrName { get; set; }
        public string DocTypes_DataSource { get; set; }
        public int DocTypes_DCCode { get; set; }
        public bool DocTypes_DCReqd { get; set; }
        public int DocTypes_DefaultNet { get; set; }
        public string DocTypes_DeleteCond { get; set; }
        public bool DocTypes_DelyWise { get; set; }
        public bool DocTypes_DiscFlag { get; set; }
        public int DocTypes_DisplayOrder { get; set; }
        public bool DocTypes_DocApprovalReq { get; set; }
        public bool DocTypes_DocAttach { get; set; }
        public bool DocTypes_DocBackward { get; set; }
        public bool DocTypes_DocReview { get; set; }
        public int DocTypes_DocWidth { get; set; }
        public bool DocTypes_DontCalcFactor { get; set; }
        public bool DocTypes_DontConsPendOrd { get; set; }
        public bool DocTypes_DontDlySchedule { get; set; }
        public bool DocTypes_DontGenIndent { get; set; }
        public bool DocTypes_DontGenReserve { get; set; }
        public bool DocTypes_DontGenWO { get; set; }
        public bool DocTypes_DontSchemeAppl { get; set; }
        public string DocTypes_EditCond { get; set; }
        public bool DocTypes_ExclConsWO { get; set; }
        public bool DocTypes_ExpandKIT { get; set; }
        public string DocTypes_ExternalApp { get; set; }
        public bool DocTypes_FasterOpr { get; set; }
        public bool DocTypes_FetchWoDet { get; set; }
        public bool DocTypes_FetchWoNo { get; set; }
        public bool DocTypes_FIFOOrder { get; set; }
        public bool DocTypes_FOC { get; set; }
        public bool DocTypes_ForceChln { get; set; }
        public bool DocTypes_ForceCirculars { get; set; }
        public bool DocTypes_ForceIndents { get; set; }
        public bool DocTypes_ForceOrder { get; set; }
        public bool DocTypes_ForceReason { get; set; }
        public string DocTypes_Formats { get; set; }
        public int DocTypes_FromBin { get; set; }
        public int DocTypes_FromStore { get; set; }
        public bool DocTypes_GenMFG { get; set; }
        public int DocTypes_GoodStore { get; set; }
        public int DocTypes_GrpKey { get; set; }
        public decimal DocTypes_GSIRate { get; set; }
        public bool DocTypes_GSTFlag { get; set; }
        public bool DocTypes_GSTNoCommon { get; set; }
        public int DocTypes_GSTNoITC { get; set; }
        public int DocTypes_GSTType { get; set; }
        public bool DocTypes_GSTTypeChange { get; set; }
        public bool DocTypes_HideAddChg { get; set; }
        public bool DocTypes_HideAddon { get; set; }
        public bool DocTypes_HideAmt { get; set; }
        public bool DocTypes_HideBatchSrl { get; set; }
        public bool DocTypes_HideDiscount { get; set; }
        public bool DocTypes_HideNarr { get; set; }
        public bool DocTypes_HideProcess { get; set; }
        public bool DocTypes_HideProduct { get; set; }
        public bool DocTypes_HideQty { get; set; }
        public bool DocTypes_HideQty2 { get; set; }
        public bool DocTypes_HideRate { get; set; }
        public bool DocTypes_HideRatePer { get; set; }
        public bool DocTypes_HideReason { get; set; }
        public bool DocTypes_HideStore { get; set; }
        public bool DocTypes_HideTax { get; set; }
        public bool DocTypes_HideUnits { get; set; }
        public bool DocTypes_HideValue { get; set; }
        public string DocTypes_HotKey { get; set; }
        public bool DocTypes_IndPending { get; set; }
        public bool DocTypes_InnerBrkp { get; set; }
        public bool DocTypes_InterBranch { get; set; }
        public bool DocTypes_ItemAttach { get; set; }
        public string DocTypes_ItemGroups { get; set; }
        public bool DocTypes_JobCurrentWork { get; set; }
        public bool DocTypes_JobworkStyle { get; set; }
        public System.DateTime DocTypes_LastDate { get; set; }
        public string DocTypes_LastDateVM { get; set; }
        public string DocTypes_LastPrefix { get; set; }
        public string DocTypes_LastSerial { get; set; }
        public int DocTypes_Level { get; set; }
        public string DocTypes_LimitFrom { get; set; }
        public string DocTypes_LimitTo { get; set; }
        public int DocTypes_LocationCode { get; set; }
        public bool DocTypes_LockAddChg { get; set; }
        public bool DocTypes_LockAddon { get; set; }
        public bool DocTypes_LockAmt { get; set; }
        public bool DocTypes_LockBatchSrl { get; set; }
        public bool DocTypes_LockDiscount { get; set; }
        public bool DocTypes_LockNarr { get; set; }
        public bool DocTypes_LockPosting { get; set; }
        public bool DocTypes_LockProcess { get; set; }
        public bool DocTypes_LockProduct { get; set; }
        public bool DocTypes_LockQty { get; set; }
        public bool DocTypes_LockQty2 { get; set; }
        public bool DocTypes_LockRate { get; set; }
        public bool DocTypes_LockRatePer { get; set; }
        public bool DocTypes_LockReason { get; set; }
        public bool DocTypes_LockStore { get; set; }
        public bool DocTypes_LockTax { get; set; }
        public bool DocTypes_LockUnits { get; set; }
        public bool DocTypes_LockValue { get; set; }
        public string DocTypes_MainType { get; set; }
        public bool DocTypes_MakePDF { get; set; }
        public decimal DocTypes_MaximumDetail { get; set; }
        public int DocTypes_MaxPrints { get; set; }
        public bool DocTypes_MfgMove { get; set; }
        public byte DocTypes_MfgType { get; set; }
        public bool DocTypes_MilestoneReqd { get; set; }
        public bool DocTypes_MoreQty { get; set; }
        public string DocTypes_MSDFormat { get; set; }
        public string DocTypes_AppBranchL { get; set; }
        public bool DocTypes_MultiLevelBOM { get; set; }
        public string DocTypes_Name { get; set; }
        public bool DocTypes_NegStock { get; set; }
        public byte DocTypes_NegWarn { get; set; }
        public bool DocTypes_NoDuplItems { get; set; }
        public bool DocTypes_NoItemEdit { get; set; }
        public bool DocTypes_NoITF { get; set; }
        public bool DocTypes_NonStock { get; set; }
        public int DocTypes_NoOfEntries { get; set; }
        public bool DocTypes_NoPrintWindow { get; set; }
        public bool DocTypes_NoReleaseAdj { get; set; }
        public bool DocTypes_OrderEditParty { get; set; }
        public string DocTypes_OrdTypes { get; set; }
        public bool DocTypes_OverReserve { get; set; }
        public bool DocTypes_PartyDisc { get; set; }
        public int DocTypes_PCCode { get; set; }
        public string DocTypes_PDFFormat { get; set; }
        public bool DocTypes_PickChlnRate { get; set; }
        public bool DocTypes_PickSOFromMember { get; set; }
        public bool DocTypes_PickSummary { get; set; }
        public string DocTypes_PostSave { get; set; }
        public bool DocTypes_PostShow { get; set; }
        public bool DocTypes_PostSummary { get; set; }
        public int DocTypes_PrefixAuto { get; set; }
        public string DocTypes_PrefixConst { get; set; }
        public int DocTypes_PrefixStyle { get; set; }
        public string DocTypes_PreSave { get; set; }
        public bool DocTypes_PrevQty { get; set; }
        public string DocTypes_PrintCond { get; set; }
        public bool DocTypes_PrintControl { get; set; }
        public bool DocTypes_PrintOnSave { get; set; }
        public int DocTypes_ProcessCode { get; set; }
        public bool DocTypes_ProductPost { get; set; }
        public string DocTypes_PROFormat { get; set; }
        public bool DocTypes_Projects { get; set; }
        public string DocTypes_QCGTRType { get; set; }
        public bool DocTypes_QCReqd { get; set; }
        public bool DocTypes_QtyTole { get; set; }
        public string DocTypes_RateFlag { get; set; }
        public bool DocTypes_RateOnMRP { get; set; }
        public int DocTypes_ReasonCategory { get; set; }
        public string DocTypes_RefDoc { get; set; }
        public string DocTypes_RefType { get; set; }
        public int DocTypes_RejStore { get; set; }
        public bool DocTypes_RequireAttach { get; set; }
        public bool DocTypes_RequireCrLimit { get; set; }
        public bool DocTypes_RequireCrPeriod { get; set; }
        public bool DocTypes_RequireHSN { get; set; }
        public bool DocTypes_RequireTIN { get; set; }
        public bool DocTypes_RequireTRNS { get; set; }
        public bool DocTypes_ReturnsType { get; set; }
        public bool DocTypes_RevStage { get; set; }
        public bool DocTypes_RoundOff { get; set; }
        public bool DocTypes_RoundTax { get; set; }
        public int DocTypes_RoundTo { get; set; }
        public bool DocTypes_SalesmanReqd { get; set; }
        public bool DocTypes_SendAlert { get; set; }
        public int DocTypes_Seq { get; set; }
        public bool DocTypes_SerTaxMul { get; set; }
        public int DocTypes_ShowStores { get; set; }
        public string DocTypes_SkipStock { get; set; }
        public bool DocTypes_SOIndPend { get; set; }
        public bool DocTypes_SOIndPending { get; set; }
        public string DocTypes_SOPFormat { get; set; }
        public string DocTypes_SourceDoc { get; set; }
        public bool DocTypes_SPAdj { get; set; }
        public bool DocTypes_StockReserve { get; set; }
        public int DocTypes_Store { get; set; }
        public bool DocTypes_SubContCombine { get; set; }
        public string DocTypes_SubType { get; set; }
        public bool DocTypes_SuppInvoice { get; set; }
        public bool DocTypes_TaxablePost { get; set; }
        public string DocTypes_Template { get; set; }
        public string DocTypes_Terms { get; set; }
        public int DocTypes_ToBin { get; set; }
        public int DocTypes_ToStore { get; set; }
        public bool DocTypes_TypeLock { get; set; }
        public bool DocTypes_UseCR { get; set; }
        public bool DocTypes_ValueOrder { get; set; }
        public string DocTypes_vAuto { get; set; }
        public bool DocTypes_WOBatch { get; set; }
        public bool DocTypes_WOEditLoss { get; set; }
        public bool DocTypes_WOEditRM { get; set; }
        public byte DocTypes_WOFetchStyle { get; set; }
        public bool DocTypes_WOFilterPro { get; set; }
        public int DocTypes_WOInterface { get; set; }
        public bool DocTypes_WOLockCapacity { get; set; }
        public bool DocTypes_WONegative { get; set; }
        // iX9: Structure from hidden fields (e.g. CountryName etc, for combo,autocomplete) 
        public List<SelectListItem> WOFetchStyleList { get; set; }
        public List<SelectListItem> SkipStockList { get; set; }
        public List<SelectListItem> NegWarnList { get; set; }
        public List<SelectListItem> vAutoList { get; set; }
        public List<SelectListItem> WOInterfaceList { get; set; }
        public List<SelectListItem> CurrConvList { get; set; }
        public List<SelectListItem> CircularsList { get; set; }
        public List<SelectListItem> GSTTypeList { get; set; }
        public List<SelectListItem> BasedTypeList { get; set; }
        public List<SelectListItem> SourceDocList { get; set; }
        public List<SelectListItem> WOStyleList { get; set; }
        public List<SelectListItem> Branches { get; set; }
        public string RefTypeName { get; set; }
        public string MainTypeName { get; set; }
        public string SubTypeName { get; set; }
        public string PDFFormatName { get; set; }
        public string ConstantName { get; set; }
        public string StoreName { get; set; }
        public string AppBranchName { get; set; }
        public string LocationCodeName { get; set; }
        public string ProcessCodeName { get; set; }
        public string ReasonCategoryName { get; set; }
        public string DCCodeName { get; set; }
        public string CashAccName { get; set; }
        public string ChequeAccName { get; set; }
        public string CreditCardAccName { get; set; }
        public string FromStoreName { get; set; }
        public string ToStoreName { get; set; }
        public string CurrNameName { get; set; }
        public string FromBinName { get; set; }
        public string ToBinName { get; set; }
        public string RejStoreName { get; set; }
        public string GoodStoreName { get; set; }
        public string QCGTRTypeName { get; set; }
        public string CategoryName { get; set; }

        // iX9: Common default Fields
        public string Document { get; set; }
        public string ENTEREDBY { get; set; }
        public System.DateTime LASTUPDATEDATE { get; set; }
        public string AUTHORISE { get; set; }
        public string AUTHIDS { get; set; }
        public string Mode { get; set; }

        // iX9: used while passing parameters from MasterGrid to Option and Back 
        public string MainType { get; set; }
        public string Controller2 { get; set; }
        public string Header { get; set; }
        public string OptionCode { get; set; }
        public string OptionType { get; set; }
        public string TableName { get; set; }
        public string Module { get; set; }
        public string ViewDataId { get; set; }
        public bool DocTypes_LockFactor { get; set; }
        public bool DocTypes_HideFactor { get; set; }
        public bool DocTypes_LockHSN { get; set; }
        public bool DocTypes_HideHSN { get; set; }
        public bool DocTypes_ApprovalRequired { get; set; }
        public bool DocTypes_PriceListReqd { get; set; }
        public bool IsSaveAs { get; set; }

        public bool CutTDS { get; set; }

        public byte GSTDocType { get; set; }
    }
}